### PR TITLE
feature(provider/openstack) implement senlin zone policy and scheduler hints

### PR DESCRIPTION
**Pull request by BrianBerzins**
* implemented senlin back zone policies
* implemented generic scheduler hints
* reworked dynamic aspects of heat templates
* added testing for dynamic aspects of heat templates

@johnrengelman

### CODE REVIEW

**Comment by edwinavalos** [comment]
@murasaki if you can sync up with master I'll go ahead and merge

**Comment by BrianBerzins** [comment]
@edwinavalos updated (again) couple of merges today :)

**Comment by edwinavalos** [comment]
@murasaki lol try again

**Comment by BrianBerzins** [comment]
@edwinavalos you're killing me man! :P

**Comment by edwinavalos** [comment]
We did it!

**Pull request merged**
