### PR TITLE
fix(aws): Eureka health when using SQL backend

### PR DESCRIPTION
**Pull request by adriengentil**
This commit fixes two issues with Eureka and the SQL backend:
* in `AmazonHealthProvider`: there is a direct relation between an instance and its Eureka health, so retrieving the health from `externalHealthProvider` led to duplicated entries in the response
* in `AmazonClusterProvider`: there is no direct relation between an application and the Eureka health, the solution I found is to use `translateInstances` which will retrieve the Eureka health for every instances linked to the application

### CODE REVIEW

**Comment by xavileon** [comment]
@spinnaker/oss-approvers PTAL

**Comment by xavileon** [comment]
hello @spinnaker/oss-approvers :) we're blocked by this to migrate clouddrive to SQL. This works internally but we're not sure this is the best approach. Who would be the best person to review an verify we're fixing this? thanks!

**Comment by robzienert** [comment]
This PR is kind of worrisome to me, can you help clear a couple things up? What is the motivation here? It feels like I missed some context.

There needs to be tests that assert this bad behavior you're seeing now and how this change fixes it. Without it, I don't feel comfortable merging.

**Comment by xavileon** [comment]
That makes sense, we'll try to provide some context and tests that shows the failure we're seeing.

**Comment by adriengentil** [comment]
Sorry for the delay, here are the details.

We are in the process of migrating Clouddriver from Redis to SQL. Our tests are showing that the health state of the instances relaying on Eureka are now reported as "unknown" in Deck when the SQL backend is activated (the instance is not attached to any TargetGroup).

**Problem with the /application endpoint**

After investigation, it shows that Deck relies on Clouddriver's API `applications/<app>/serverGroups`:

Using Redis:

    {
        "type": "aws",
        "targetGroups": [],
        "serverGroupManagers": [],
        "instanceCounts": {
          "up": 1,
          "unknown": 0,
          "total": 1,
          "starting": 0,
          "outOfService": 0,
          "down": 0
        },
        "cluster": "my-test-cluster",
        "cloudProvider": "aws",
        "capacity": {
          "min": 1,
          "max": 1,
          "desired": 1
        },
        "application": "my-app",
        "account": "my-account",
        "instances": [
          {
            "name": "i-fffffffffffffffff",
            "id": "i-fffffffffffffffff",
            "healthState": "Up",
            "health": [
              {
                "type": "Amazon",
                "state": "Unknown"
              },
              {
                "type": "Discovery",
                "status": "UP",
                "state": "Up"
              }
            ],
          }

Using SQL: 

    {
        "type": "aws",
        "targetGroups": [],
        "serverGroupManagers": [],
        "instanceCounts": {
          "up": 0,
          "unknown": 1,
          "total": 1,
          "starting": 0,
          "outOfService": 0,
          "down": 0
        },
        "cluster": "my-test-cluster",
        "cloudProvider": "aws",
        "capacity": {
          "min": 1,
          "max": 1,
          "desired": 1
        },
        "application": "my-app",
        "account": "my-account",
        "instances": [
          {
            "name": "i-fffffffffffffffff",
            "id": "i-fffffffffffffffff",
            "healthState": "Unknown",
            "health": [
              {
                "type": "Amazon",
                "state": "Unknown"
              }
            ],
          }

As you can see, the health state coming from Eureka is not reported anymore.

I dove into the code and it led me to the call of [getAllApplications](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy#L162) in the code of the `applications` API. This call performs a query like:

    (select body as `body`, null as `id`, null as `rel_id`, null as `rel_type` from cats_v1_health where application = 'my-spinnaker-app') union all (select null as `body`, rel.id as `id`, rel.rel_id as `
    rel_id`, rel.rel_type as `rel_type` from cats_v1_health as `r` join cats_v1_health_rel as `rel` on (rel.id=r.id) where (r.application = "my-spinnaker-app") group by rel_id, id, rel_type)

Which filters the heath states on the spinnaker application name, but the Eureka provider stores the instance health under the [Eureka's server application name](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy#L109):

    +---------------------------------------------------------------------+------------------------------------------------------------------------------------------------+---------------------------------+
    | id                                                                  | agent                                                                                          | application                     |
    +---------------------------------------------------------------------+------------------------------------------------------------------------------------------------+---------------------------------+
    | aws:health:i-fffffffffffffffff:my-account:eu-west-1:Discovery       | http://eu-west-1.eureka.my-account.my-internal-dns:8080/eureka-server/v2/EurekaCachingAgent    | my-eureka-controller-name       |
    +---------------------------------------------------------------------+------------------------------------------------------------------------------------------------+---------------------------------+

I don't know how it is working with Redis, but it's getting the Eureka health trough the call of `getAllApplication`.

**Problem with the /instances endpoint**

On the opposite, I noticed that the call to [getAll](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceProvider.groovy#L71) returns the Eureka health state when using SQL because the call goes through all the health relations of the instance, which is not the case with Redis. 

You can see here the duplicated Eureka health that I get when I call the `/instances/<account>/<region>/<instance>` endpoint with the SQL backend:

     "health": [
        {
          "type": "Amazon",
          "state": "Unknown",
          "healthClass": "platform"
        },
        {
          "vipAddress": "my-eureka-controller-name",
          "type": "Discovery",
          "statusPageUrl": "http://ip-99-99-99-99.eu-west-1.compute.internal:80/info",
          "status": "UP",
          "state": "Up",
          "eurekaStatus": "UP",
          "eurekaAccountName": "my-account",
          "discoveryType": "Eureka",
          "availabilityZone": "eu-west-1c",
          "application": "my-eureka-controller-name",
          "amiId": "ami-fffffffffffffffff",
          "allowMultipleEurekaPerAccount": false,
          "accountId": "999999999999",
          "healthCheckUrl": "http://ip-99-99-99-99.eu-west-1.compute.internal:80/health",
          "hostName": "ip-99-99-99-99.eu-west-1.compute.internal",
          "instanceId": "i-fffffffffffffffff",
          "instanceType": "c5d.2xlarge",
          "ipAddress": "99.99.99.99",
          "lastUpdatedTimestamp": 1583314302524,
          "overriddenStatus": "UNKNOWN",
          "secureVipAddress": "my-eureka-controller-name"
        },
        {
          "vipAddress": "my-eureka-controller-name",
          "type": "Discovery",
          "statusPageUrl": "http://ip-99-99-99-99.eu-west-1.compute.internal:80/info",
          "status": "UP",
          "state": "Up",
          "eurekaStatus": "UP",
          "eurekaAccountName": "my-account",
          "discoveryType": "Eureka",
          "availabilityZone": "eu-west-1c",
          "application": "my-eureka-controller-name",
          "amiId": "ami-fffffffffffffffff",
          "allowMultipleEurekaPerAccount": false,
          "accountId": "999999999999",
          "healthCheckUrl": "http://ip-99-99-99-99.eu-west-1.compute.internal:80/health",
          "hostName": "ip-99-99-99-99.eu-west-1.compute.internal",
          "instanceId": "i-fffffffffffffffff",
          "instanceType": "c5d.2xlarge",
          "ipAddress": "99.99.99.99",
          "lastUpdatedTimestamp": 1583314302524,
          "overriddenStatus": "UNKNOWN",
          "secureVipAddress": "my-eureka-controller-name"
        }
      ],
      "healthState": "Up",


I agree this PR is more a hack than anything else since I use `translateInstances` in `AmazonClusterProvider.groovy` which relies on `getAll` to retrieve the details of the instance and by transitivity, get the Eureka health.

Ideally, the SQL cache should have the exact same behaviour than the Redis one, but I'm not sure how to fix that. Should we fix the way Eureka stores its data? Or should we change the way we query the data?

I hope it's clearer !

**Comment by robzienert** [comment]
Thanks for the explanation. I will run this deploy this into a test environment tomorrow to verify before merging. I still want to see tests around this functionality before merging so that we don't regress in the future.

**Comment by xavileon** [comment]
@cfieber is this ok to merge it?

**Comment by adriengentil** [comment]
@cfieber can you have a look? Thanks!

**Pull request merged**
