### PR TITLE
provider/kubernetes: Image pull secrets are now populated automatically rather than by requirement.

### PR DESCRIPTION
**Pull request by lwander**
…

Also fixed an agent caching typo

### CODE REVIEW

**Comment by lwander** [comment]
@cfieber, @ajordens - do either of you have an idea as to why the build is failing? it gets as far as `:cats:cats-core:compileTestGroovy` and then it hangs.

**Comment by lwander** [comment]
Going to try again now that there is less pressure on (metal) travis: here is the last failed build: https://travis-ci.org/spinnaker/clouddriver/builds/108339003

**Comment by duftler** [comment]
Lgtm.

**Comment by duftler** [comment]
Needs a rebase.

**Pull request merged**
