### PR TITLE
Make docker registry integration great again

### PR DESCRIPTION
**Pull request by tomaslin**
- change manifest endpoint to @HEAD from @GET
- allow configurable timeout for docker registry client calls
- add docker endpoint to swagger

### CODE REVIEW

**Comment by tomaslin** [comment]
@lwander PTAL

**Comment by lwander** [comment]
This is a *yuge* improvement. LGTM

**Comment by tomaslin** [comment]
clouddriver has tiny hands

**Comment by ttomsu** [comment]
# 👌

**Pull request merged**
