### PR TITLE
fix(aws): revert change that is breaking clouddriver on Jenkins

### PR DESCRIPTION
**Pull request by plumpy**
Reverts spinnaker/clouddriver#4968

### CODE REVIEW

**Comment by fieldju** [comment]
Cant we just set the default env var for jenkins that is what we did for github actions

**Comment by fieldju** [comment]
https://github.com/spinnaker/clouddriver/blob/master/build.gradle#L72

This needs to be set as an env var for the AWS sdk if you are not running on an AWS instance

**Comment by plumpy** [comment]
Yeah, we can do that, but is this likely to bite customers too? Why wasn't this an issue before?

**Comment by fieldju** [comment]
> 
> 
> Yeah, we can do that, but is this likely to bite customers too? Why wasn't this an issue before?

Because you don't have unit tests, we can delete the unit test and things will be happy :(

**Comment by fieldju** [comment]
Basically if you instantiate an AWS client it needs to be configured for a region, were are doing that in the unit test.

**Comment by plumpy** [comment]
Discussed this on Slack, @fieldju is going to send a small PR to fix the issue.

**Pull request closed without merging**
