### PR TITLE
chore(kubectl): upgrade kubectl version from 1.20.6 to 1.22.17

### PR DESCRIPTION
**Pull request by AdanUrbanReyesArmory**

### CODE REVIEW

**Review by danielGz — APPROVED** [review]

**Comment by dbyron-sf** [comment]
@AdanUrbanReyesArmory can you tell us how you've tested this please?

**Comment by AdanUrbanReyesArmory** [comment]
@dbyron-sf 
after applying the changes I run the integrations test `./gradlew :clouddriver-kubernetes:integrationTest`

**Comment by dbyron-sf** [comment]
What about in a real-life spinnaker installation?

**Comment by AdanUrbanReyesArmory** [comment]
Yes, the installation,  deployment & delete pipelines were **ok**; I follow the next steps:  
1. Compile the changes with `./gradlew clouddriver-web:installDist -x test `
2. Create the clouddriver image with: `docker build --file Dockerfile.slim --tag armory/clouddriver:kubectl-upgrade-slim-1.30.x .`
3. Modify `spec.spinnakerConfig.service-settings.clouddriver.artifactId` value to use the created image (`armory/clouddriver:kubectl-upgrade-slim-1.30.x`)
4. Apply changes
5. Assert the new image was deployed with `kubectl -n spinnaker describe deployment/spin-clouddriver | grep Image:`
6. Assert the new kubectl version was installed with  `kubectl -n spinnaker exec -it deployments/spin-clouddriver -- sh -c 'kubectl version --short'`
7. Create pipeline with two stages, one for deploy and  the other for delete an nginx image

**Comment by dbyron-sf** [comment]
That's pretty good.  If possible, I'd like that to run for long enough to build up a bit more confidence, and exercise it with more kinds of resources -- like kinds that may be newly deprecated, or removed, as well as newly introduced kinds.

**Comment by AdanUrbanReyesArmory** [comment]
Running for a whole day without any issue, pipelines every minute with two stages (deploy and delete) for the following kinds: 
1. ReplicaSet
2. Service
3. Ingress
4. DaemonSet
5. Deployment
6. Pod
7. StatefulSet
8. Job
9. CronJob
10. NetworkPolicy
11. Namespace
12. CustomResourceDefinition

**Review by mattgogerly — APPROVED** [review]

**Comment by dbyron-sf** [comment]
Sorry this fell off my radar for a bit.  I think this is probably OK, but I'm still paranoid about it.  At Salesforce, we've been running with kubectl 1.21.14 for a couple of months so I have good confidence bumping that far.  I've been meaning to put up a PR for that...Has 1.22.17 been running in production at Armory?

**Review by jasonmcintosh — APPROVED** [review]

**Pull request merged**
