### PR TITLE
fix(google): fixing UpsertGoogleAutoscalingPolicyAtomicOperation missing Autowired for objectMapper and cacheView

### PR DESCRIPTION
**Pull request by shlomodaari**
Fixing the following [issue](https://github.com/spinnaker/spinnaker/issues/6963) 
It was introduced as part of this [PR](https://github.com/spinnaker/clouddriver/pull/6057/files#diff-77886cd9f754611f6844f38a9d1eaa13a7306a5c311d58aa07fa7aff2ab1de88L67)

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Can you add a test that demonstrates the bug?

**Comment by shlomodaari** [comment]
@dbyron-sf I updated the tests that it will check for this. 
Previously, the tests didn't cover it, so we couldn't see it failing.

**Comment by dbyron-sf** [comment]
Sorry, didn't see it there, thanks!

**Review by jasonmcintosh — APPROVED** [review]

**Comment by jasonmcintosh** [comment]
@Mergifyio backport release-1.33.x release-1.34.x

**Pull request merged**
