### PR TITLE
Additional fix for issue 1632, not able to find AMI with encrypted sn…

### PR DESCRIPTION
**Pull request by jcusa**
After my original fix for [https://github.com/spinnaker/spinnaker/issues/1632](url), We noticed that there was another scenario where the fix wasn't covering for that same issue. That's when the encrypted AMI was found in both source and target account. In such a case, the code would resolve ami from the source first and proceed with that image and try to modify it, which will again cause the error because encrypted AMI can't be shared with target. 

The proposed fix here is simply looking in target account first.  If found, then great, use it and no additional work is needed since that's where we are launching it.  This makes sense even in cases where we are dealing with normal non encrypted AMIs. We have tested with this fix for quite some time in several environments. thank you.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Looks reasonable to me, @cfieber any concerns?

**Comment by jcusa** [comment]
branch was outdated. I have rebased it. thank you.

**Comment by jcusa** [comment]
@anotherchrisberry can it be merged? thank you.

**Comment by anotherchrisberry** [comment]
Let's find out!

**Comment by cfieber** [comment]
@jcusa I'm pushing a fix for a regression this introduced in which tags are not synchronized

I'm not sure if an encrypted AMI affects whether it can be tagged or not, if so you'll need to find a fancy workaround to detect if the AMI is encrypted and shortcircuit the tag sync bit

**Comment by jcusa** [comment]
@cfieber thanks a lot for the heads up, and sorry for the trouble it caused. Somehow we didn't notice this issue in our environment. Tagging encrypted AMI doesn't appear to be an issue. changing owner definitely didn't work.

**Pull request merged**
