### PR TITLE
feat(provider/openstack) - add support for AZs

### PR DESCRIPTION
**Pull request by msilpala**

### CODE REVIEW

**Comment by johnrengelman** [comment]
LGTM

**Comment by edwinavalos** [comment]
@msilpala or @johnrengelman if you can rebase I can go ahead and merge.

**Comment by msilpala** [comment]
Can do.

**Comment by msilpala** [comment]
Rebased.

**Comment by msilpala** [comment]
@edwinavalos Any chance of a quick release with this code included?

**Comment by edwinavalos** [comment]
@msilpala https://github.com/spinnaker/clouddriver/releases/tag/v1.760.0 fyi

**Pull request merged**
