### PR TITLE
chore(dependencies): spinnaker-gradle-project 5.2.1

### PR DESCRIPTION
**Pull request by cfieber**
Upgrades spinnaker-dependencies to 1.3.0
Upgrades gradle to 4.10.1

Closes #3086

### CODE REVIEW

**Comment by lwander** [comment]
:sweat: man @jtk54 can't believe you had spinbot close that

**Comment by cfieber** [comment]
I know it's not actually a bot, it's just @jtk54 making me dance to his tune

**Comment by lwander** [comment]
He totally approved the PR that added this functionality: https://github.com/spinnaker/spinnaker/pull/3225

**Comment by jtk54** [comment]
image

**Comment by jtk54** [comment]
I'm pulling strings behind the scenes.

**Comment by lwander** [comment]
hmmm
image

**Pull request merged**
