### PR TITLE
Refactorig for Azure kato and oort classes under Azure clouddriver

### PR DESCRIPTION
**Pull request by milismsft**
Refactorig for Azure kato and oort classes under Azure clouddriver namespace.

Refactoring for Azure specific resources and templates.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
As this only affects Azure files, I'm inclined to merge it (once it's rebased). @ajordens @cfieber any objections?

**Comment by ajordens** [comment]
Looks reasonable to me

**Comment by robfletcher** [comment]
@milismsft can you rebase this against master. Looks like @anotherchrisberry and @ajordens have already reviewed it but we can't merge it until it's up to date with the latest changes.

**Comment by dpodder** [comment]
Thanks @robfletcher for taking a look! Rebase completed. Please let us know if there are any other issues.

**Pull request merged**
