### PR TITLE
fix(provider/cf): fix regression caused by clusterSummaries

### PR DESCRIPTION
**Pull request by zachsmith1**
Fix a regression caused by clusterSummaries. ClusterSummaries should not fully hydrate the servergroups, hence needs to be changed to NONE for details. The underlying method that is ran got reverted to its original state until we can revisit this set of features at a later date. A test was added to ensure the functionality works as expected.

### CODE REVIEW

**Comment by zachsmith1** [comment]
@spinnakerbot add-label backport-candidate

**Review by german-muzquiz — APPROVED** [review]

**Comment by german-muzquiz** [comment]
This was the PR that introduced the regression: https://github.com/spinnaker/clouddriver/pull/4749 , so the only version affected is `1.22`

**Comment by german-muzquiz** [comment]
@Mergifyio release-1.22.x

**Comment by german-muzquiz** [comment]
@Mergifyio backport release-1.22.x

**Pull request merged**
