### PR TITLE
fix(provider/gce): s/it/cacheData/ in zonal svg caching agent.

### PR DESCRIPTION
**Pull request by jtk54**
@ewiseblatt fyi.

### CODE REVIEW

**Comment by ewiseblatt** [comment]
LGTM

**Comment by edwinavalos** [comment]
@jtk54 is there a bug this fixes described somewhere?

**Comment by jtk54** [comment]
This was introduced fairly recently in a Moniker-related change in Clouddriver -- I believe this code isn't released yet in a proper Spinnaker release.

**Comment by lwander** [comment]
:sweat:

**Pull request merged**
