### PR TITLE
fix(provider/kubernetes): Fixed statefulset and daemonset volumesourc…

### PR DESCRIPTION
**Pull request by chlung**
About this PR,

Patch https://github.com/spinnaker/clouddriver/pull/2276 PR into 1.5.x branch.

Thanks.

…e bugs.

feat(provider/kubernetes): split out required & optional artifacts (#2273)

fix(provider/docker): update bearer_token to access_token (#2274)

We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

### CODE REVIEW

**Comment by chlung** [comment]
@lwander Please review.  Original PR already merged into master.  I just patched 1.5.x branch.  thx.

**Comment by chlung** [comment]
@lwander Can you review and merge this PR?  thanks.

**Comment by lwander** [comment]
Ah I see there is

**Comment by chlung** [comment]
@lwander thanks

**Pull request merged**
