### PR TITLE
Massive removal of 'GoogleCloudProvider' instance object. Replaced with static call.

### PR DESCRIPTION
**Pull request by ttomsu**
*Review second commit only*: This PR is based off of https://github.com/spinnaker/clouddriver/pull/434

This one has been on my list for a long time to clean up. @duftler @lwander PTAL.

tag: https://github.com/spinnaker/spinnaker/issues/712

### CODE REVIEW

**Comment by cfieber** [comment]
Nice change - I will push the same through AWS

GoogleCloudProvider still exists and is still a `@Component` in the ApplicationContext (and will continue to be) to enable programatic discovery of all the active providers.

**Comment by cfieber** [comment]
(LGTM)

**Comment by gregturn** [comment]
I'll do the same for Cloud Foundry! (Although I didn't code it into the Keys methods, for some reason).

**Comment by gregturn** [comment]
https://github.com/spinnaker/clouddriver/pull/438

**Pull request merged**
