### PR TITLE
refactor(provider/gce): Reworks security group keyspace lookups.

### PR DESCRIPTION
**Pull request by jtk54**
WIP -- DO NOT MERGE.

This PR is to test the new keyspace split for XPN firewalls. @seanpeters86 PTAL.

### CODE REVIEW

**Comment by seanpeters86** [comment]
Just built and deployed this to our dev spinnaker and had some pretty amazing improvements. Checked our largest application and saw the following improvements:

| Item                   | Before     | After      |
| --------------- | --------- | -------- |
| Cluster view      | 2.5m       | 48s        |
| Resources Size | 45.5 MB | 39.8 MB |
| Page Load         | 3.2m      | 1.8m     |
| Security Groups Size | 6.8 MB | 1.6 MB |
| Security Groups Load | 10.77s | 2.33s |

**Comment by robzienert** [comment]
@ezimanyi Do we want this?

**Comment by ezimanyi** [comment]
I suspect we can close this given it's WIP and hasn't been updated in a few months, but first CC'ing @maggieneterval who is working on some GCE performance issues and may be interested in this change.

**Comment by maggieneterval** [comment]
We have an issue tracking this that we can keep open (https://github.com/spinnaker/spinnaker/issues/4373), but we can close this PR for now until someone has bandwidth to investigate how this change broke implicit contracts with Deck.

**Pull request closed without merging**
