### PR TITLE
feat(huaweicloud): first commit for huaweicloud

### PR DESCRIPTION
**Pull request by zengchen1024**
This pr includes the security functions used in huawei cloud clouddriver.  The cloud provider proposal is https://github.com/spinnaker/community/issues/17

### CODE REVIEW

**Comment by zengchen1024** [comment]
@robzienert Could you take a look at this pr, thanks! One question, must I change to java? At present, I have completed all the works for clouddriver and deck, and they work well.

**Comment by emjburns** [comment]
Hi @zengchen1024, thanks for referencing your proposal! Yes, we would like all back end code to be in java instead of groovy. Our conventions are [here](https://www.spinnaker.io/community/contributing/back-end-code/#choice-of-language).

**Comment by zengchen1024** [comment]
@emjburns  Thanks for your comment. I will update.

**Comment by zengchen1024** [comment]
@robzienert @emjburns Could you take a look at this pr. Thanks very much!

**Pull request closed without merging**
