### PR TITLE
feat(provider/azure): Support health extension for extensions profile

### PR DESCRIPTION
**Pull request by EasyAsABC123**
- Adds support for health Extensions as well as enables the ability to add more extensions in the future using new interfaces.
- Unit tested
- Verified in Azure environment
- Backwards compatible

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
resolves https://github.com/spinnaker/spinnaker/issues/6343

**Comment by christopherdoak** [comment]
I can confirm this was tested in our spinnaker environment and works as intended.
Thanks!

**Comment by neil-yechenwei** [comment]
Thanks @EasyAsABC123 for the PR. Could you resolve the conflicts before the PR review? Thanks in advance.

**Comment by EasyAsABC123** [comment]
@neil-yechenwei until the other PR is merged reviewing this one is pointless as it will just break again.  Can you push anyone to merge: #5217

**Comment by EasyAsABC123** [comment]
@neil-yechenwei ready for your review now

**Comment by neil-yechenwei** [comment]
LGTM

**Comment by EasyAsABC123** [comment]
@ajordens merge when ready! 👍  thanks

**Comment by EasyAsABC123** [comment]
thanks @ajordens

**Pull request merged**
