### PR TITLE
feat: Add the possibility to update the default handler for the Global Resource Property Registry

### PR DESCRIPTION
**Pull request by shlomodaari**
* feat: Add possibility to re-set default handler for Global Resource Property Registry.

* feat: Add not null check for defaultHandler param.

### CODE REVIEW

**Comment by dbyron-sf** [comment]
This definitely needs tests, but also motivation for why we need/want this.

**Comment by shlomodaari** [comment]
@dbyron-sf This is part of a code that was backported to 1.28 1.29 1.30 but was missed in 1.31 and you approved it last year tbh. 
https://github.com/spinnaker/clouddriver/blob/release-1.29.x/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java
https://github.com/spinnaker/clouddriver/blob/release-1.30.x/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java
https://github.com/spinnaker/clouddriver/blob/release-1.32.x/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java

Let me know if you have any additional questions please

**Comment by shlomodaari** [comment]
Can be closed now we found the missing backport :)

**Comment by edgarulg** [comment]
mergify never created the backport for 1.31.x: https://github.com/spinnaker/clouddriver/pull/6323

**Pull request closed without merging**
