### PR TITLE
feat(aws): upgrade awscli

### PR DESCRIPTION
**Pull request by kevinawoo**

### CODE REVIEW

**Comment by pieterza** [comment]
Could we kindly get this one merged?  Possibly even backported into current release as without it EKS native auth via awscli is broken.

**Comment by robzienert** [comment]
Yes, just have to wait for the PR to update. ... and that takes forever and then I forget 😭

**Comment by costimuraru** [comment]
We're having the same issue with halyard: https://github.com/spinnaker/halyard/pull/1382

**Comment by pieterza** [comment]
@robzienert I see the bot has tagged it for 1.16, but I feel this should be backported for 1.15 too, if possible?  We still currently run our own custom image with this fix as EKS deployments using native AWS auth literally does not work without it.

**Comment by pieterza** [comment]
@spinnakerbot cherry-pick 1.15

**Comment by pieterza** [comment]
@spinnakerbot cherry-pick 1.14

**Pull request merged**
