### PR TITLE
handle cross account security group ingress

### PR DESCRIPTION
**Pull request by claymccoy**

### CODE REVIEW

**Comment by claymccoy** [comment]
@ajordens @cfieber @anotherchrisberry 
Any feedback on this would be appreciated.

**Comment by gregturn** [comment]
Was this last "merge branch master" supposed to be a rebase against latest master branch?

**Comment by anotherchrisberry** [comment]
@claymccoy Can you provide a high-level summary of the changes here? Looks like a pretty big change set, and I'm not totally sure where to start looking to understand what's different now.

**Comment by claymccoy** [comment]
@gregturn It wasn't a rebase. It is just the update branch button in Github to keep it current.

**Comment by gregturn** [comment]
I don't like that approach, because it merges master into your branch. For me, it's preferable to rebase against master, moving your commits to instead be based against the latest copy of master. Avoids having to review conflicts, etc. And if you use "-i", it provides the means to squash things into a simpler commit to inspect.

https://www.atlassian.com/git/tutorials/merging-vs-rebasing/

**Comment by ajordens** [comment]
+1 I also prefer a proper rebase.

    update = !git fetch upstream && git rebase upstream/`git rev-parse --abbrev-ref HEAD`

is the git alias I use to handle the rebase locally. 

Relies on a proper upstream being set:

    git remote add upstream git@github.com:spinnaker/XXX.git

**Comment by claymccoy** [comment]
@anotherchrisberry 
This changes upsert security group to handle cross account security groups. It also allows IP security groups, and an append ingress only mode but that is tangential.
The API changes are added fields in UpsertSecurityGroupDescription. The main logic changes are in UpsertSecurityGroupAtomicOperation.

Some controversial things that I did was remove some validation from UpsertSecurityGroupDescriptionValidator. It wasn't as useful in a cross account world, and I feel like those validators should really be validating input, if it is pulling in all the AWS info needed to do the operation then that seems too far.

SecurityGroupIngressConverter normalized ingress so that we can compare existing and new ingress.

SecurityGroupLookupFactory gets the caching code out of the operation.

And a lot of it is unit tests.

**Comment by claymccoy** [comment]
Rebase changes history and for that reason is usually is not done in an open PR. It is only done because of the the new requirement before merging which I am not exactly a fan of. The rebase/merge is a different discussion that should probably happen somewhere else.

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
