### PR TITLE
Revert "feat(ecs): update application caching agent to store applicat…

### PR DESCRIPTION
**Pull request by allisaurus**
…ion and relationships (#5234)"

This reverts commit f4579543892892331cb058e47a7a8d3ca0b5ab86.

### CODE REVIEW

**Comment by deverton** [comment]
What's the reason to revert this?

**Comment by allisaurus** [comment]
@deverton we decided we wanted to do additional validation testing before this went out in an official release. It was originally merged in to allow interested parties to test it out by deploying the release candidate, and that's still an option post-1.26 branch cut. 

Were you interested in testing it out or are you currently effected by https://github.com/spinnaker/spinnaker/issues/6084 ?

**Comment by deverton** [comment]
Yes, we're hitting this particular issue as we've been on-boarding ECS clusters. The search from the Spinnaker UI frontpage takes 8+ minutes to run with only a few ECS accounts added. Before it was near instant. Search from other sections (e.g. for applications) is still instance. So I assume it's something to do with the infrastructure search.

We see very high CPU and query rate on the RDS instance backing clouddriver during this time as well.

**Comment by deverton** [comment]
Oh, I misunderstood. I thought this had been released in 1.25 and this was reverting it. Looks like the original patch never made it in to a release. I'll keep an eye on it for 1.26.

**Pull request merged**
