### PR TITLE
feat(ecs): suspend/resume autoscaling during disable/enable service operations

### PR DESCRIPTION
**Pull request by clareliguori**
Fixes spinnaker/spinnaker#4707

Depends on spinnaker/kork#371 before this can be merged

### CODE REVIEW

**Comment by clareliguori** [comment]
The above kork change upgrading the AWS SDK is part of kork v6.5.0, now waiting on a kork version bump in clouddriver

**Comment by emjburns** [comment]
@clareliguori I merged that kork bump into clouddriver

**Comment by louisjimenez** [comment]
@clareliguori are you looking to get this into 1.16?

**Comment by clareliguori** [comment]
@louisjimenez yes, it would be great to get this in for 1.16 if you haven't cut the release yet

**Pull request merged**
