### PR TITLE
provider/openstack: Update client to release version.

### PR DESCRIPTION
**Pull request by derekolk**
closes https://github.com/spinnaker/spinnaker/issues/1077

### CODE REVIEW

**Comment by derekolk** [comment]
@spinnaker/reviewers @cfieber @lwander

**Comment by lwander** [comment]
LGTM - anyone mind if I merge?

**Comment by lwander** [comment]
Sorry, one more rebase and we'll have this merged

**Comment by derekolk** [comment]
@lwander rebased again 👍

**Pull request merged**
