### PR TITLE
fix(kubernetes/v1): Handle possible NPEs with autoscalers in Kubernetes v1 provider

### PR DESCRIPTION
**Pull request by emptywee**
Handlig possible NPEs which break clouddriver caching agents cycles, thus cache gets inaccurate/incomplete, resulting in missing data in the UI and produces long force cache refresh task cycles.

Addressing this sort of problems:
```
 java.lang.NullPointerException: Cannot get property 'name' on null object
     at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-2.5.7.jar:2.5.7]
     at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190) ~[groovy-2.5.7.jar:2.5.7]
     at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46) ~[groovy-2.5.7.jar:2.5.7]
     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298) ~[groovy-2.5.7.jar:2.5.7]
     at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiConverter$_attachAutoscaler_closure21.doCall(KubernetesApiConverter.groovy:823) ~[clouddriver-kubernetes.jar:na]
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.7.jar:2.5.7]
     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.7.jar:2.5.7]
     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.7.jar:2.5.7]
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.7.jar:2.5.7]
...
     at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiConverter.attachAutoscaler(KubernetesApiConverter.groovy:823) ~[clouddriver-kubernetes.jar:na]
     at com.netflix.spinnaker.clouddriver.kubernetes.v1.model.KubernetesV1ServerGroup.<init>(KubernetesV1ServerGroup.groovy:173) ~[clouddriver-kubernetes.jar:na]
...
```

### CODE REVIEW

**Comment by emptywee** [comment]
@ezimanyi Sure, whatever is better in your opinion. This was breaking caching cycles and the cluster state was shown incorrect/inaccurate from the spinnaker's standpoint. I did not want to patch clouddriver every time there's a new release, so decided to send at least this sort of patch. If #4060 fixes it, and it's going to be released in 1.16 (will it?), I am fine with closing this PR unmerged. If 1.16 is going to be affected by this bug, then it's probably worth fixing it one way or another and release as a minor bugfix release. What's your call going to be, Eric?

**Comment by emptywee** [comment]
Let's close this PR then. I am still on 1.15, but had to patch 1.14 too. Didn't know that 1.16 was going to get the fix. Once released, I'll test #4096 with 1.16 and see if it actually fixes this.

**Comment by ezimanyi** [comment]
@emptywee : I'll cherry-pick #4096 into 1.15 for you as well; it should end up in 1.15.6.  Thanks again for bringing this up!

**Comment by emptywee** [comment]
Much appreciated. I'll test 1.15.6 once it's been released and report back if it fixes the issue for us. Thanks again, Eric.

**Comment by emptywee** [comment]
@ezimanyi Eric, I just tested clouddriver from release 1.15.6 - no more NPEs observed. Thanks once again for cherry-picking #4096 into 1.15!

**Pull request closed without merging**
