### PR TITLE
config(googlecloudsdkversion): Upgraded the google cloud sdk version from 412.0.0 to 476.0.0 in clouddriver.

### PR DESCRIPTION
**Pull request by sanopsmx**
https://github.com/spinnaker/spinnaker/issues/6954

Upgraded the google cloud sdk version from 412.0.0 to 476.0.0

Upgraded both Docker java 11 & 17 files. 

Tested the deployments and working fine.

### CODE REVIEW

**Comment by sanopsmx** [comment]
@j-sandy @kirangodishala @mattgogerly @dbyron0 
Pls can you review these changes and provide your feedback.

**Comment by mattgogerly** [comment]
I forget what the SDK is used for - is it just authentication? Have there been any notable or breaking changes between these versions?

**Comment by sanopsmx** [comment]
> I forget what the SDK is used for - is it just authentication? Have there been any notable or breaking changes between these versions?

Yes ,authentication, authorization and deployment. Do not see any breaking changes.

Here is the link of the 476.0.0 version release notes.

https://cloud.google.com/sdk/docs/release-notes

**Comment by sanopsmx** [comment]
@mattgogerly 

I see the major app engine update from 476.0.0.

App Engine

Use java21 as the default runtime for app.yaml generated configuration. This change is compatible with gcloud app deploy command, when there is no app.yaml configuration for Java projects (Maven, or Gradle, or simple jar). Instead of using a java17 runtime target, App Engine deploys the application using the java21 runtime with an F2 instance class. To continue using the java17 runtime, create an app.yaml file, and specify runtime: java17.


Updated the Java SDK to version 2.0.27 build from the open source project https://github.com/GoogleCloudPlatform/appengine-java-standard/releases/tag/v2.0.27.

**Review by nemesisOsorio — APPROVED** [review]
LGTM

**Review by nemesisOsorio — CHANGES_REQUESTED** [review]
should we change other Docker files like `Dockerfile.slim`?

**Comment by sanopsmx** [comment]
> should we change other Docker files like `Dockerfile.slim`?

Yes...good catch.....Modified the slim files as well.

**Comment by sanopsmx** [comment]
> @mattgogerly
> 
> I see the major app engine update from 476.0.0.
> 
> App Engine
> 
> Use java21 as the default runtime for app.yaml generated configuration. This change is compatible with gcloud app deploy command, when there is no app.yaml configuration for Java projects (Maven, or Gradle, or simple jar). Instead of using a java17 runtime target, App Engine deploys the application using the java21 runtime with an F2 instance class. To continue using the java17 runtime, create an app.yaml file, and specify runtime: java17.
> 
> Updated the Java SDK to version 2.0.27 build from the open source project https://github.com/GoogleCloudPlatform/appengine-java-standard/releases/tag/v2.0.27.

Appengine deployments working fine. attached screenshots.
Screenshot from 2024-05-23 14-28-28
Screenshot from 2024-05-23 14-28-33

**Pull request merged**
