### PR TITLE
provider/cloudfoundry: Handle credentials for a clean install

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Comment by gregturn** [comment]
@spinnaker/reviewers PTAL

**Comment by duftler** [comment]
Looks like unit test failed on this one.

**Comment by gregturn** [comment]
@duftler Doh! Fixed the unit test and rebased.

**Comment by duftler** [comment]
LGTM, but, as expected, needs another rebase.

**Comment by gregturn** [comment]
Rebased.

**Pull request closed without merging**
