### PR TITLE
Merge kato-aws into clouddriver-aws

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by ajordens** [comment]
PTAL @cfieber 

Should be a straight up merge of the two artifacts. I did merge `KatoAWSConfig` with AwsConfiguration.

**Comment by ajordens** [comment]
Hold off on this @cfieber ... I'm just running some more in-depth tests locally.

**Comment by ajordens** [comment]
Looks good so far, I've done a deploy locally.

No particular rush to merge it down, I can build on top of it locally.

**Comment by cfieber** [comment]
LGTM - fire ze missiles whenever you are happy

**Pull request merged**
