### PR TITLE
fix(appengine): restore batch calls, bump client library

### PR DESCRIPTION
**Pull request by danielpeach**
This reverts commit 8db951459adfd0259d1a2ca95323099ad4509e6b.

### CODE REVIEW

**Comment by danielpeach** [comment]
ping @jtk54 could you please test this out with GCE?

**Comment by jtk54** [comment]
Yep, checking now.

**Comment by jtk54** [comment]
LGTM, works fine with both GCE and GAE enabled - no `no JSON input` exceptions.

**Comment by danielpeach** [comment]
Awesome, thanks.

**Pull request merged**
