### PR TITLE
refactor(kubernetes): Update fabric8 client to 2.3.1 for StatefulSet

### PR DESCRIPTION
**Pull request by dsimonto**
StatefulSet model is not available in the fabric8 client currently used.  This upgrades fabric8 to the latest client.  Also had to import the Job model class from a different location.

### CODE REVIEW

**Comment by dsimonto** [comment]
@lwander please review.  This sets the stage for adding StatefulSet to the mix.

**Comment by lwander** [comment]
Have you run through the various operations locally, and if so, against what k8s cluster versions?

**Comment by dsimonto** [comment]
I ran the clouddriver unit tests which all passed.  I also ran these ops against Minikube 0.14.0 (kubernetes 1.5)  from Spinnaker: create/delete load balancer, create/destroy server group, resize server group, terminate instance of server group.  I did not try anything with Jobs (I don't have a Job container).

Does the integration test verify these operations?

**Comment by lwander** [comment]
Awesome, we'll run the integration test tonight after it's merged.

**Comment by lwander** [comment]
It verifies them, but it's part of a larger suite that takes a while to run, and we're trying to keep those clean/passing for the next two weeks while we practice our release process. A sanity check before merging goes a long way while we try to get this process in place.

**Pull request merged**
