### PR TITLE
fix(openstack): error exception message while deleting server group

### PR DESCRIPTION
**Pull request by yejingtao**
Detail in issue 3174
https://github.com/spinnaker/spinnaker/issues/3174

### CODE REVIEW

**Comment by yejingtao** [comment]
@lwander hi, it's not my last commit,  I cann't use 'git commmit --amend' to change now, should I use 'git rebase' command? 
This is my first time PR, Can you give me some advice? Thank you.

**Comment by yejingtao** [comment]
@lwander 
Step1: make a clean dir and clone project form my fork
Step2: git remote add upstream https://github.com/spinnaker/clouddriver.git
Step3: git fetch upstream and git merge upstream/master
Step4: push new code into my fork
All above is ok!
Step5: git rebase -i upstream/master, and squash
Step6: git push, but not success~ CRY!
If there is no better way, can I rebase my local fork and then send a new PR?

**Comment by lwander** [comment]
Oh I forgot to mention, since you rewrote history with `git rebase`, you need `git push -f origin <branch>` to overwrite the remote history.

**Comment by lwander** [comment]
(The `-f` flag is the key modifier here)

**Comment by lwander** [comment]
Looks good, nice work!

**Pull request merged**
