### PR TITLE
fix (ecs): Unstable deployments for task definitions with more than one container  (#5544)

### PR DESCRIPTION
**Pull request by atyutyunnik**
The original code will not finish deployment and will eventually time out, in spite of task being successfully deployed by ECS and running (spinnaker/spinnaker#5544)

        "containers": [:

            "containers": [
                {
                    "networkBindings": [],
                    "networkInterfaces": [],
                },
                {
                    "lastStatus": "RUNNING",
                    "networkBindings": [
                        {
                            "bindIP": "0.0.0.0",
                            "containerPort": 8080,
                            "hostPort": 32773,
                            "protocol": "tcp"
                        }
                }]

### CODE REVIEW

**Comment by atyutyunnik** [comment]
> can we add unit tests to verify that tasks with network bindings in containers other than the first one are correctly evaluated?

Normally, that's the first thing I do when introducing a change, but I was quite in a hurry with the fix for my own purposes and I also need to figure out how these particular unit tests work.

**Comment by allisaurus** [comment]
quoting @atyutyunnik from the slack convo about this issue:

> I have re-verified it with the original 1.19.0 - the problem is there, UT detects it; applied the fix - UT is happy

🎉

**Comment by clareliguori** [comment]
@spinnakerbot cherry-pick 1.19

**Comment by allisaurus** [comment]
@spinnakerbot cherry-pick 1.18

**Comment by atyutyunnik** [comment]
For 1.18, you have to use PR# 4411. PR4409 is not compatible with the code base

**Pull request merged**
