### PR TITLE
feat(provider/ecs): Create server group Atomic Operation stub

### PR DESCRIPTION
**Pull request by BrunoCarrier**
feat(provider/ecs): Create server group Atomic Operation stub

### CODE REVIEW

**Comment by BrunoCarrier** [comment]
@tomaslin @robzienert Is this architecture in alignment with what you had on your mind?

**Comment by robzienert** [comment]
Can you rebase your branches when you submit PRs? It's hard to determine what is and isn't coming along for the ride.

**Comment by BrunoCarrier** [comment]
@robzienert I've rebased, and will do so for future PRs

**Comment by BrunoCarrier** [comment]
@ajordens @cfieber adding you to PR

**Pull request merged**
