### PR TITLE
refactor(provider/azure): Clean AppGateway descriptions

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
After PR https://github.com/spinnaker/deck/pull/3439, the region is no longer being passed as an array

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
@rguthriemsft @scotmoor @clguimanmsft PTAL

**Comment by rguthriemsft** [comment]
LGTM

**Comment by EricJizbaMSFT** [comment]
@spinnaker/reviewers PTAL

**Comment by EricJizbaMSFT** [comment]
@duftler @ewiseblatt can you take quick look? Should be an easy one.

Also is the 'spinnaker/reviewers' group gone? I'm not sure who best to ping if a PR has been open for a while

**Comment by duftler** [comment]
The  'spinnaker/reviewers' group still exists. I think there is a some group you need to be added to to be able to ping it. I'll ask @cfieber to see if you are in that group.

**Pull request merged**
