### PR TITLE
fix(kubernetes): handle images without registry

### PR DESCRIPTION
**Pull request by danielpeach**
@lwander please review.

@ethanfrogers FYI

### CODE REVIEW

**Comment by lwander** [comment]
Just curious, what's prompting this?

**Comment by ethanfrogers** [comment]
@lwander 
image

**Comment by lwander** [comment]
How did that happen? There isn't a clear standard (AFAIK) around resolving that registry. Docker CLI will assume `index.docker.io` and K8S will assume `gcr.io`, which is why I'm nervous about assuming some default.

**Comment by ethanfrogers** [comment]
@danielpeach and I have been working through an issue in Deck that prevents images like `nginx:latest` or `ethanfroger/spindemo:1.0.0` from being populated when Cloning a ServerGroup or using it as template. I have preexisting Deployments that use this image syntax(?) that aren't being populated. We believe we've fixed the problem in Deck but when we both cloned an SG with that style image it resulted in the above image.

**Comment by lwander** [comment]
Ok makes sense - but are those `nginx:latest` images coming from Spinnaker, or other sources?

**Comment by ethanfrogers** [comment]
They're preexisting Deployments we have in Kubernetes.

**Comment by lwander** [comment]
Ah fair, LGTM!

**Pull request merged**
