### PR TITLE
feat(lambda): Add AmazonOperation annotation Lambda operations

### PR DESCRIPTION
**Pull request by aufarg**
Add AmazonOperation annotation on Lambda operation converters

Fixes: https://github.com/spinnaker/spinnaker/issues/6355

### CODE REVIEW

**Comment by aufarg** [comment]
@cfieber @robzienert 

Hi! Can I have a review on this? IIRC it used to work but IIUC there's a modification on Clouddriver that changes how operations are validated and now this doesn't work anymore

**Comment by shyamsfo** [comment]
@zachsmith1 Can you do that?

**Comment by zachsmith1** [comment]
@aufarg I see you did this for a few of the operations, however it appears there are more of them. Can we also include the others in this PR?

**Comment by zachsmith1** [comment]
@aufarg any luck here?

**Comment by zachsmith1** [comment]
@mergify refresh

**Comment by mattgogerly** [comment]
@Mergifyio update

**Review by mattgogerly — APPROVED** [review]

**Pull request closed without merging**
