### PR TITLE
fix(manifest-replicas): ReplicaSet Source-Capacity

### PR DESCRIPTION
**Pull request by nhtzr**
Change: Use version suffixes to populate replicas when using use-source-capacity annotation

### CODE REVIEW

**Review by danielGz — APPROVED** [review]

**Comment by nhtzr** [comment]
@Mergifyio backport release-1.28.x release-1.27.x

**Comment by mattgogerly** [comment]
Can you explain what's currently broken and how this fixes it?

**Comment by nhtzr** [comment]
@mattgogerly `use-source-capacity` annotation is meant to query the currently used `replicas` field from the manifest in the cluster. The behavior seems to run fine with non-versioned manifests. However, the current implementation fails to take into account the versioning that spinnaker usually adds to ReplicaSets. The fix introduces extra to logic to query the `replicas` field from the correct manifest name.

**Comment by mrampton** [comment]
@nhtzr -- would you mind adding some tests?

**Comment by nhtzr** [comment]
@mrampton updated

**Comment by nhtzr** [comment]
@spinnaker/reviewers  Hi, please let me know if I'm missing anything.

**Comment by nhtzr** [comment]
@ovidiupopa07 Hi, please let me know if I'm missing anything.

**Review by ovidiupopa07 — APPROVED** [review]
LGTM

**Comment by nhtzr** [comment]
Added Integration tests for both use-source-capacity cases

**Review by ovidiupopa07 — APPROVED** [review]
Lgtm

**Comment by ovidiupopa07** [comment]
@Mergifyio update

**Pull request merged**
