### PR TITLE
fix(provider/kubernetes): upsertScalingPolicy will patch existing autoscaler instead of re-creating

### PR DESCRIPTION
**Pull request by alex-marchenko**
UpsertKubernetesAutoscalerAtomicOperation will now update existing HPA instead of deleting&creating it again.

### CODE REVIEW

**Comment by robzienert** [comment]
ping @lwander

**Comment by alex-marchenko** [comment]
@lwander, are you interested in this PR?
If not, I'll close it.

**Comment by lwander** [comment]
The build is unhappy though: https://travis-ci.org/spinnaker/clouddriver/builds/345300733#L652

**Comment by alex-marchenko** [comment]
@lwander, I've fixed the build.

**Pull request merged**
