### PR TITLE
Adding integration tests for AWS EC2 provider

### PR DESCRIPTION
**Pull request by pdk27**
* Adding integration tests for AWS EC2 provider for CreateServerGroup operation (with launch configuration / launch template settings enabled)
* Adding AWS provider integration tests to Github workflow

#### Sample integ test run:
Look for `AWS EC2 Provider Integration Tests` in https://github.com/pdk27/clouddriver/runs/2090227653?check_suite_focus=true

#### Successful run (shows tests summary):
image

### CODE REVIEW

**Comment by pdk27** [comment]
@cfieber @ajordens

**Review by german-muzquiz — COMMENTED** [review]
Thanks for making the effort to increase spinnaker quality! Overall I only have some comments based on the experience writing kubernetes integration tests, maybe they're of help.

The focus of each test case was to validate some functionality at a level that a user can understand with the least amount of context as possible. For example, looking at `Deploy (Manifest)` stage it is composed of several tasks, where each task may or may not result in a request to clouddriver:
image
I decided that each test case covers _all_ requests to clouddriver done to successfully deploy a manifest, instead of testing a single request. This has the effect that test cases can be designed at a business/acceptance level, making it easy to write them with clear given/when/then sections according to behavior driven development. It also has the effect of making it obvious when a test case is needed: basically every field in the stage configuration can be a separate test case. On the other hand, test cases are longer and may fail at different points.

**Review by ajordens — APPROVED** [review]
I don't have a tremendous amount of experience with the existing integration tests for other providers, not against having similar tests for aws. 

Don't see a blocker to starting with these.

**Comment by ajordens** [comment]
Are you happy with the state of these @pdk27 and would you like them merged?

**Comment by pdk27** [comment]
> Are you happy with the state of these @pdk27 and would you like them merged?

Thanks Adam. I do have the permissions to merge now (yay!) 
Once I address German's comments, I will take this forward.

**Comment by pdk27** [comment]
> Thanks for making the effort to increase spinnaker quality! Overall I only have some comments based on the experience writing kubernetes integration tests, maybe they're of help.
> 
> The focus of each test case was to validate some functionality at a level that a user can understand with the least amount of context as possible. For example, looking at `Deploy (Manifest)` stage it is composed of several tasks, where each task may or may not result in a request to clouddriver:
> image
> I decided that each test case covers _all_ requests to clouddriver done to successfully deploy a manifest, instead of testing a single request. This has the effect that test cases can be designed at a business/acceptance level, making it easy to write them with clear given/when/then sections according to behavior driven development. It also has the effect of making it obvious when a test case is needed: basically every field in the stage configuration can be a separate test case. On the other hand, test cases are longer and may fail at different points.

Makes sense. I have little context into pipelines and its stages. I thought until I gain more context in that area / other contributors who are already familiar want to add more tests, AWS provider could use some integ tests for each supported operation. These tests can definitely be improved and made more focused on customer's view point in the future. Thanks for the insight.

**Review by german-muzquiz — APPROVED** [review]

**Pull request merged**
