### PR TITLE
fix(cloudfoundry): skip API calls for apps that won't be cached

### PR DESCRIPTION
**Pull request by mattgogerly**
Moving the "should cache" checks prior to the call to map so that unnecessary API calls aren't made for apps that won't be cached anyway.

### CODE REVIEW

**Comment by zachsmith1** [comment]
@mattgogerly this LGTM but ideally we get some kind of test. Would this be easily testable?

**Comment by mattgogerly** [comment]
> @mattgogerly this LGTM but ideally we get some kind of test. Would this be easily testable?

Will give it a go. The tests for this method are quite sparse so might have to come up with something.

**Comment by mattgogerly** [comment]
@zachsmith1 added some verify() calls to the test from #5427

**Review by zachsmith1 — APPROVED** [review]

**Comment by zachsmith1** [comment]
@Mergifyio backport release-1.27.x

**Pull request merged**
