### PR TITLE
Mutating AWS server group calls operate only on `asgs`.

### PR DESCRIPTION
**Pull request by duftler**
All manner of asgName|serverGroupName, region|regions and asgs are supported on the requests and coerced to asgs via LegacyToAsgsDescriptionPreProcessor.
AWS resize is handled specially via its own dedicated ResizeAsgDescriptionPreProcessor due to the presence of `capacity` within `asgs`.
asgName and regions are deprecated on all the descriptions.

### CODE REVIEW

**Comment by duftler** [comment]
@cfieber or @ajordens please review.
As discussed, these changes are necessary so that orca can be modified to pass `region` on these calls instead of `regions`.
Will first need to massage the Azure operations to accept `region` instead of `regions` (starting on that now).

**Comment by duftler** [comment]
This PR does not contain any breaking changes w.r.t. to callers.

**Comment by milismsft** [comment]
I thought that having multiple regions rather then one region allows me when creating pipeline stages to select/specify multiple ones and execute certain operations on them simultaneously (such as destroy, enable, disable). Was that not the case?

**Comment by duftler** [comment]
Yes, that still works (and will continue to work) fine. The reason that works is that orca synthesizes individual clouddriver calls (one per region) from the original multi-region request.

**Comment by duftler** [comment]
As it is now, orca always passes single-item `regions` lists to clouddriver for those stages.

**Comment by duftler** [comment]
Rebased.

**Comment by ajordens** [comment]
LGTM

I'll do a bit more testing on the affected Descriptions before we push it out to `prod`.

**Comment by duftler** [comment]
Cool. Good to merge?

**Pull request merged**
