### PR TITLE
Fix for insufficiently unique storage account name

### PR DESCRIPTION
**Pull request by JargoonPard**
Also removed a few unused parameters and fixed a typo

### CODE REVIEW

**Comment by JargoonPard** [comment]
@ajordens PTAL

**Comment by anotherchrisberry** [comment]
LGTM - any objections to merging @ajordens ?

**Comment by ajordens** [comment]
LGTM

**Comment by JargoonPard** [comment]
Rebased. Please merge while the rebase holds... :-)

**Pull request merged**
