### PR TITLE
feat(aws): Use Kork's BaseProvider

### PR DESCRIPTION
**Pull request by nabuskey**
This is the first step for AWS provider to use `CredentialsRepository`  introduced in https://github.com/spinnaker/governance/blob/master/rfc/account-management.md. 

- Use the new `BaseProvider` introduced in #4930 
- Move provider configuration to helper functions

### CODE REVIEW

**Comment by nimakaviani** [comment]
@ajordens @plumpy  fyi this is the first of the series of PRs related to the account registration RFC. your help in pushing these through is much appreciated.

**Comment by ajordens** [comment]
Giving this a whirl internally.

**Comment by nimakaviani** [comment]
thanks!

**Comment by ajordens** [comment]
Looks good to my eyes so far. Any objection to me merging @nimakaviani?

**Comment by nimakaviani** [comment]
great. let's do it. we will be sending the second PR soon. thanks!

**Review by ajordens — APPROVED** [review]

**Pull request merged**
