### PR TITLE
feat(lambda): additional properties for stream event source mappings

### PR DESCRIPTION
**Pull request by jaredstehler**
Adds additional properties used in stream-based lambda event source mappings (i.e. kinesis)

### CODE REVIEW

**Comment by jaredstehler** [comment]
closed as dupe of #5318

**Comment by jaredstehler** [comment]
this was errantly closed

**Comment by zachsmith1** [comment]
@jaredstehler any kind of testing we can do here? Looks simple enough but not sure if any of those additional fields can cause issues if they are explicitly null?

**Comment by jaredstehler** [comment]
I'm not sure there's much we can do in a unit test, since the aws-sdk seems to just pass the values on to the API. That said, looking into the `UpdateEventSourceMappingRequest` and `CreateEventSourceMappingRequest` classes, these fields are all defined as nullable default null.

**Review by zachsmith1 — APPROVED** [review]
LGTM

**Comment by jaredstehler** [comment]
@Mergifyio refresh

**Comment by zachsmith1** [comment]
@Mergifyio refresh

**Comment by jaredstehler** [comment]
Do i need to do anything to resolve this mergify failure? I enabled it to access that repo through my account.

**Comment by zachsmith1** [comment]
@mergify refresh

**Pull request merged**
