### PR TITLE
fix(titus): Set env variable to map to spinnaker account

### PR DESCRIPTION
**Pull request by aravindmd**
Set env variable to map to spinnaker account , this has to be accessible within the task(container) for some automated work flows.

### CODE REVIEW

**Comment by ajordens** [comment]
Curious if this would be confusing given other udf fields are typically `NETFLIX_` prefixed.

**Comment by aravindmd** [comment]
> Curious if this would be confusing given other udf fields are typically `NETFLIX_` prefixed.

Good point , i think it would be ok to add the `NETFLIX_` prefix here.

**Comment by aravindmd** [comment]
> > Curious if this would be confusing given other udf fields are typically `NETFLIX_` prefixed.
> 
> Good point , i think it would be ok to add the `NETFLIX_` prefix here.

Any other concerns other than the naming , i'll add the prefix.

**Comment by ajordens** [comment]
Nothing from me, I think it'll be fine.

**Review by ajordens — APPROVED** [review]

**Pull request merged**
