### PR TITLE
fix(provider/kubernetes): Rebasing the code After merging to Master (Issue no: 1989)

### PR DESCRIPTION
**Pull request by prashantvicky**
@lwander 
Due to Issue in the re basing , i have to pull the Master code and merged my changes to it.
This pull request is in the continuation of https://github.com/spinnaker/clouddriver/pull/1947
 
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

### CODE REVIEW

**Comment by prashantvicky** [comment]
@lwander we need to merge this pull request

**Comment by lwander** [comment]
Is this still needed or was it merged in another PR?

**Comment by prashantvicky** [comment]
@lwander its depends , in this PR we are just wanted to convey a user that he is using older version of kubernetes , Just logging message in Log "Cannot fetch Daemonsets Required Kubernetes VERSION>=1.6"
So its good to have but not really required.

**Comment by robzienert** [comment]
@lwander To close or not to? 🤔

**Comment by lwander** [comment]
Closing since this was covered by a later PR

**Pull request closed without merging**
