### PR TITLE
fix(kubernetes): Empty port causing NPE during caching

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Comment by viglesiasce** [comment]
Can we get this one merged? It's blocking my work on updating the Spinnaker Helm chart.

**Comment by duftler** [comment]
Sorry for the delay.

**Comment by viglesiasce** [comment]
Thanks @duftler !!

**Comment by viglesiasce** [comment]
@lwander needs another merge from master

**Comment by lwander** [comment]
Whoops, sorry! here we go...

**Comment by viglesiasce** [comment]
Thanks @lwander @duftler!

**Comment by lwander** [comment]
Np, are your docker images running at `:latest`/`:master`? If not, want me to cut a release?

**Comment by lwander** [comment]
https://github.com/spinnaker/clouddriver/releases/tag/v1.599.0

**Pull request merged**
