### PR TITLE
chore(build): update Mergify config

### PR DESCRIPTION
**Pull request by mattgogerly**

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Similar to https://github.com/spinnaker/deck/pull/9785 + https://github.com/spinnaker/deck/pull/9786, right?  Any differences worth calling out?

PS Thanks for doing this.

**Comment by mattgogerly** [comment]
> Similar to [spinnaker/deck#9785](https://github.com/spinnaker/deck/pull/9785) + [spinnaker/deck#9786](https://github.com/spinnaker/deck/pull/9786), right? Any differences worth calling out?
> 
> PS Thanks for doing this.

Yup, looks like we're using strict across all repos and it was removed on the 6th.

Only difference is Deck's CI is slightly more complicated so the queue condition is different, but otherwise identical.

**Review by dbyron-sf — APPROVED** [review]

**Comment by link108** [comment]
@mergifyio backport release-1.27.x release-1.26.x

**Comment by link108** [comment]
@Mergifyio backport release-1.25.x

**Pull request merged**
