### PR TITLE
fix(amazon): explicitly declare volumeType for default block devices

### PR DESCRIPTION
**Pull request by anotherchrisberry**
**For review only - should not be merged yet**

`gp2` is going to be the default volume type at some point in the very near future, which will cause us grief at Netflix when we update our AWS client version.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
cc @vfilanovsky

**Comment by robzienert** [comment]
👍

**Comment by vfilanovsky** [comment]
Looks good, let's roll it out

**Comment by anotherchrisberry** [comment]
I will get this rolled out next week.

**Pull request merged**
