### PR TITLE
instance caching bug fix

### PR DESCRIPTION
**Pull request by scotmoor**
Fix bug in server group caching agent. Includes some refactoring.

### CODE REVIEW

**Comment by scotmoor** [comment]
@spinnaker/netflix-reviewers  PTAL

**Comment by scotmoor** [comment]
@spinnaker/netflix-reviewers ping

**Comment by cfieber** [comment]
LGTM

**Comment by JargoonPard** [comment]
@cfieber rebased

**Comment by scotmoor** [comment]
Thanks for taking care of this. Wifi has been iffy here at the pool

**Comment by duftler** [comment]
Ha, life's rough sometimes.

**Comment by tomaslin** [comment]
@JargoonPard can you squash commits instead of merging master?

**Comment by scotmoor** [comment]
@tomaslin rebased

**Pull request merged**
