### PR TITLE
Short-circuit detach operation if there are no detachable instances

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
My only concern is that pending instances will eventually come up and then not be detached, which would be a surprise.

**Comment by anotherchrisberry** [comment]
But maybe that's okay. This change is better than current behavior.

**Comment by anotherchrisberry** [comment]
:shipit:

**Comment by ajordens** [comment]
Not a big deal if the PENDING instances come up, another request will inevitably come in to terminate them.

**Pull request merged**
