### PR TITLE
core/search: Always use default query identifier extractor results, a…

### PR DESCRIPTION
**Pull request by duftler**
…nd add to those any custom identifier extractor results.

### CODE REVIEW

**Comment by duftler** [comment]
Without this fix, anytime an aws account is configured, no other providers can surface standalone instance results.

**Comment by duftler** [comment]
@anotherchrisberry please review.

**Comment by anotherchrisberry** [comment]
That is some dense code. I believe you that it works.

**Comment by duftler** [comment]
Here is the executive summary, Senator:

Before this change, the `identifierExtractors` map was queried for a custom identifier extractor for a given `type` (e.g. `instances` or `serverGroups`). If one was found, it was asked to produce a set of identifiers that would then looked up in the cache. If one was not found, the default extractor was used.

Now, the default extractor is always used, and the identifiers extracted from any custom identifier extractor are added to the identifiers produced by the default extractor.

The reason I made this change is that the custom identifier extractor for `instances` in `AwsProvider` would not return any identifiers unless the queries happened to match the regex defined there.

**Comment by cfieber** [comment]
The reason the instance identifier thing went in is that it was prohibitively slow to scan the instance collection (which is what the default identifier provider does)

We've since made some changes to trim down that instance collection (we were creating duplicate entries in there at one point) so it may no longer be an issue

At the very least, there is no reason to use both providers in there - if it is going to call the default then the instances will be there and calling the instance specific extractor will just add duplicate identifiers

If it is too slow we can figure out a way to differentiate id extractors by provider or something like that

**Comment by duftler** [comment]
As per our offline discussion, I've killed off custom extractors here: https://github.com/spinnaker/clouddriver/pull/604

**Pull request merged**
