### PR TITLE
provider/docker: Replace empty repository list with _catalog results.

### PR DESCRIPTION
**Pull request by lwander**
@duftler 

Just for you, @tomaslin :wink: 

When a user omits the `repositories` field of a `dockerRegistry` config in `clouddriver.yml`, clouddriver will now try to populate the list of repositories by calling the `/_catalog` endpoint of the docker registry.

### CODE REVIEW

**Comment by tomaslin** [comment]
LGTM. Wonder if we want this behavior to be opt-in so not to take down a registry by accident.

**Comment by lwander** [comment]
Hah, maybe, it's only called once per registry per clouddriver initialization, and the bigger registries disable the `/_catalog` endpoint for exactly that reason. I'd rather keep the config simple.

**Comment by tomaslin** [comment]
don't we want this to be called every time the listData is called? Otherwise if I push a new image to my repo, I will never see it

**Comment by lwander** [comment]
Ah, you're totally right. I wouldn't be worried about the the size of the response to the `/_catalog` request, since the number of repositories will still be an order of magnitude or two lower than the number of tags & digests retrieved. 

But, if we estimate 1KB per manifest (which we need for the digest), and we are pointing at a largeish registry with ~1,000 repositories of 100 tags each we are looking at ~100MB of data per refresh cycle. Clouddriver refreshes every 30s, so that's about 3MB/s. I don't think that's enough to knock over a registry, but will probably get you throttled if it's public. WDYT?

**Comment by tomaslin** [comment]
TBH I'm less concerned about DDoSing a registry than about the images not being indexed.

**Comment by lwander** [comment]
That's true - I meant you're right, I'll fix the PR to pick up changes to the repo list with `/_catalog`, but I'm not sure we need an extra flag turn on that behavior.

**Comment by lwander** [comment]
It now refreshes the repo list on every cache load cycle.

**Comment by tomaslin** [comment]
should change the loglevel of docker client to none

**Pull request merged**
