### PR TITLE
fix(provider/aws): Only describe instance health for ELBs (#2699)

### PR DESCRIPTION
**Pull request by dmart**
fixes https://github.com/spinnaker/spinnaker/issues/2699

### CODE REVIEW

**Comment by robzienert** [comment]
Reason we didn't hit this at Netflix is because we proxy all of our calls through Edda, which no-ops the call. Whoopsies.

**Comment by staciegravy** [comment]
@spinnakerbot cherry-pick 1.10

**Comment by staciegravy** [comment]
@spinnakerbot cherry-pick 1.11

**Comment by ezimanyi** [comment]
@spinnakerbot cherry-pick 1.12

**Pull request merged**
