### PR TITLE
Added openstack instance operations getInstance and getConsoleOutput

### PR DESCRIPTION
**Pull request by derekolk**
https://github.com/spinnaker/spinnaker/issues/896

### CODE REVIEW

**Comment by derekolk** [comment]
@spinnaker/reviewers

**Comment by drmaas** [comment]
@spinnaker/reviewers

**Comment by lwander** [comment]
LGTM, solid start on caching. I would implement the Application and Cluster caching agents next, since these will get you the most mileage in terms of showing stuff in the UI. 

OK to merge?

**Comment by derekolk** [comment]
Fine by me ... Thanks for the heads up.  Was just thinkng about what next to work on.  Will start with Application, then Cluster since it looks like a BEAST!

**Pull request merged**
