### PR TITLE
fix(aws/cloudformation) Disable cloudformation cache agent

### PR DESCRIPTION
**Pull request by amanya**
Since we implemented ondemand cache in spinnaker/clouddriver/pull/5276, we believe the caching agent is not needed and can cause issues with AWS rate limiting.

This PR is for removing it.

### CODE REVIEW

**Comment by amanya** [comment]
@Mergifyio update

**Comment by amanya** [comment]
@ajordens @jeyrschabu @aravindmd Could you review this PR please? Sorry for taking too long to fix the build.

**Comment by jaredstehler** [comment]
I applied this patch and my cfn deploys with changesets didn't recognize any changes; the cache response was continually the same. I attempted to apply this diff to re-declare and register as an (on-demand) agent but it still didn't work.

```
diff --git a/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationAgent.java b/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationAgent.java
index 1d54f9d65..a056a6b60 100644
--- a/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationAgent.java
+++ b/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationAgent.java
@@ -29,6 +29,7 @@ import com.netflix.spinnaker.cats.agent.*;
 import com.netflix.spinnaker.cats.cache.CacheData;
 import com.netflix.spinnaker.cats.cache.DefaultCacheData;
 import com.netflix.spinnaker.cats.provider.ProviderCache;
+import com.netflix.spinnaker.cats.provider.ProviderRegistry;
 import com.netflix.spinnaker.clouddriver.aws.AmazonCloudProvider;
 import com.netflix.spinnaker.clouddriver.aws.cache.Keys;
 import com.netflix.spinnaker.clouddriver.aws.provider.AwsInfrastructureProvider;
@@ -43,7 +44,7 @@ import java.util.stream.Collectors;
 import lombok.extern.slf4j.Slf4j;
 
 @Slf4j
-public class AmazonCloudFormationAgent implements OnDemandAgent, AccountAware, AgentIntervalAware {
+public class AmazonCloudFormationAgent implements Agent, OnDemandAgent, AccountAware, AgentIntervalAware {
   private final AmazonClientProvider amazonClientProvider;
   private final NetflixAmazonCredentials account;
   private final String region;
@@ -73,6 +74,11 @@ public class AmazonCloudFormationAgent implements OnDemandAgent, AccountAware, A
     return AwsInfrastructureProvider.PROVIDER_NAME;
   }
 
+  @Override
+  public AgentExecution getAgentExecution(ProviderRegistry providerRegistry) {
+    return (agent) -> {};
+  }
+
   @Override
   public String getOnDemandAgentType() {
     return getAgentType();
@@ -160,7 +166,8 @@ public class AmazonCloudFormationAgent implements OnDemandAgent, AccountAware, A
     return onDemandEntriesToReturn;
   }
 
-  private String getAgentType() {
+  @Override
+  public String getAgentType() {
     return String.format(
         "%s/%s/%s", account.getName(), region, AmazonCloudFormationAgent.class.getSimpleName());
   }
diff --git a/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java b/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
index 32997b601..b5c917d6d 100644
--- a/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
+++ b/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
@@ -190,6 +190,12 @@ public class ProviderHelpers {
             new AmazonCertificateCachingAgent(
                 amazonClientProvider, credentials, region.getName(), objectMapper, registry));
 
+        if (dynamicConfigService.isEnabled("aws.features.cloud-formation", false)) {
+          newlyAddedAgents.add(
+              new AmazonCloudFormationAgent(
+                  amazonClientProvider, credentials, region.getName(), registry));
+        }
+
         if (credentials.getEddaEnabled()
             && !eddaTimeoutConfig.getDisabledRegions().contains(region.getName())) {
           newlyAddedAgents.add(
```

**Comment by amanya** [comment]
I'm closing the PR as we don't have bandwith to continue working with it. Sorry about that :(

**Pull request closed without merging**
