### PR TITLE
initial implementation of server groups caching

### PR DESCRIPTION
**Pull request by scotmoor**
Added caching for Azure server groups. Includes some minor bug fixes

### CODE REVIEW

**Comment by scotmoor** [comment]
@cfieber @ajordens @duftler PTAL

**Comment by cfieber** [comment]
working through on_demand handling with @scotmoor

**Comment by scotmoor** [comment]
@cfeiber updated based on our discussion. PTAL

**Comment by scotmoor** [comment]
err. @cfieber

**Pull request merged**
