### PR TITLE
fix(kubernetes): address crd delete error

### PR DESCRIPTION
**Pull request by rbadillo**
When you try to delete a Kubernetes CRD via Spinnaker UI (kubernetesRawResources Tab) you get an error.

The issue is happening when Spinnaker tries to delete a CRD. The problem is that Kubernetes Kind was being passed as None causing the following error:

Screen Shot 2021-03-29 at 3 50 34 PM

Logs:

```
2021-03-25 19:19:37.759 ERROR 1 --- [tionProcessor-0] c.n.s.c.o.DefaultOrchestrationProcessor  : com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor$KubectlException: Failed to delete none/mytestcrd from engineering: error: the server doesn't have a resource type "none"
	at com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor.delete(KubectlJobExecutor.java:154)
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.lambda$delete$12(KubernetesCredentials.java:475)
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.runAndRecordMetrics(KubernetesCredentials.java:614)
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.runAndRecordMetrics(KubernetesCredentials.java:599)
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.delete(KubernetesCredentials.java:471)
	at com.netflix.spinnaker.clouddriver.kubernetes.op.handler.CanDelete.delete(CanDelete.java:43)
	at com.netflix.spinnaker.clouddriver.kubernetes.op.manifest.KubernetesDeleteManifestOperation.lambda$operate$0(KubernetesDeleteManifestOperation.java:65)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at com.netflix.spinnaker.clouddriver.kubernetes.op.manifest.KubernetesDeleteManifestOperation.operate(KubernetesDeleteManifestOperation.java:57)
	at com.netflix.spinnaker.clouddriver.kubernetes.op.manifest.KubernetesDeleteManifestOperation.operate(KubernetesDeleteManifestOperation.java:31)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:118)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$CallableWrapper.call(TimedCallable.java:81)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.java:45)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:117)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$wrapCallableForPrincipal$0(AuthenticatedRequest.java:272)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.java:45)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This PR fixes the problem by injecting the correct Kubernetes Kind to the Delete functions.

Screen Shot 2021-03-29 at 3 48 12 PM

Issue: https://github.com/spinnaker/spinnaker/issues/6390

### CODE REVIEW

**Review by german-muzquiz — COMMENTED** [review]
As I can see the issue is that as you said, clouddriver assigns a `KubernetesKind` of `NONE` to the handler that does deletion, and that's what makes it fail.

Seems that we have a deeper problem here because the handlers should already know the kubernetes kind needed to interact with that resource. In your proposed solution the kind is being passed as a parameter to `delete` method instead of using the one it already has internally. This may work in this case, but [patch also shares this problem](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanPatch.java#L38), so this uncovers the fact that `Patch (Manifest)` stage may not be working for CRDs either.

A better solution would be that these handlers (there is one handler for every kubernetes kind) have the reference for the real kind instead of using `NONE`. When spinnaker discovers CRDs it already has logic for creating their corresponding `KubernetesKind` object dynamically, so we could leverage this dynamic CRD registration for adding specific handlers for each CRD.

These handlers are accesed through the [property registry](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java), so we can add there another collection for `crdProperties` that needs to be filled when discovering CRDs. This dicovery happens to be around the [crdSupplier](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java#L316) function.

**Comment by rbadillo** [comment]
Ignore this PR

**Comment by xavileon** [comment]
hi @rbadillo did you address this issue in another PR? we've seen the same problem and we're wondering if this is fixed by any other PR and into which release. Thanks!

**Comment by xavileon** [comment]
Thanks German!

**Pull request closed without merging**
