### PR TITLE
fix(provider/kubernetes): allow cache data to be serailized/deserialized

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Comment by ajordens** [comment]
What is different about k8s that needs this?

That retrofitDefault group dependency doesn’t seem like the right one to add to cats-core (cats-core is basically dep free and retrofitDefault must be more than bare Jackson?)

**Comment by lwander** [comment]
Every other provider creates a custom `MutableCacheData` class that extends `CacheData` just for this purpose. This is the start to consolidating all those different implementations. 

Yeah let me find a better dependency

**Comment by ajordens** [comment]
`jackson` is passable, but you really only need jackson-annotations.

`compile "com.fasterxml.jackson.core:jackson-annotations:${spinnaker.version('jackson')}"`

For whatever reason spinnaker-dependencies (wrongly!) has:

```
jacksonAnnotations: "com.fasterxml.jackson.core:jackson-databind:${versions.jackson}"
```

Otherwise this seems reasonable. Worth noting that the groovy `MutableCacheData` has `[:].withDefault { [] as Set }` so this won't be a simple drop-in replacement.

**Comment by lwander** [comment]
Neat, switched to the `jacksonAnnotations`. Should I open a spinnaker-dependencies PR to fix that package name? I'm asking because it might break some things in weird ways.

Yeah good point on the `.withDefault`

**Comment by ajordens** [comment]
Sure, let's fix `spinnaker-dependencies` ... I think it's just a typo as we also have `jacksonDatabind` referencing the exact same artifact. 

Otherwise, let's ship it.

**Comment by cfieber** [comment]
the .withDefault bit can probably be worked around via java 8 map createIfAbsent

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker-dependencies/pull/131

**Pull request merged**
