### PR TITLE
fix(cloudfoundry): Fixes issue with URI not being recognized.

### PR DESCRIPTION
**Pull request by rvazquezglez**
fix(cloudfoundry): Fixes issue with URI not being recognized.

The URL not being picked by the regex has a `/v1.0` path. These changes handle it.

### CODE REVIEW

**Review by zachsmith1 — APPROVED** [review]
Lgtm

**Review by german-muzquiz — APPROVED** [review]

**Comment by rvazquezglez** [comment]
@spinnakerbot add-label backport-candidate

**Comment by link108** [comment]
@Mergifyio backport release-1.25.x

**Comment by link108** [comment]
@Mergifyio backport release-1.23.x release-1.24.x

**Pull request merged**
