### PR TITLE
provider/openstack - Refactor server group naming conventions

### PR DESCRIPTION
**Pull request by derekolk**
closes https://github.com/spinnaker/spinnaker/issues/1156

### CODE REVIEW

**Comment by derekolk** [comment]
@spinnaker/reviewers

**Comment by drmaas** [comment]
LGTM

**Comment by lwander** [comment]
LGTM

**Comment by derekolk** [comment]
@lwander Rebased

**Comment by derekolk** [comment]
@lwander PTAL rebased again

**Pull request merged**
