### PR TITLE
provider/google: Server group caching agents should be authoritative …

### PR DESCRIPTION
**Pull request by duftler**
…w.r.t. applications.

### CODE REVIEW

**Comment by duftler** [comment]
@lwander please review.

**Comment by lwander** [comment]
I don't think this is the right fix, since both of those caching agents will encounter the same set of applications. It's probably best to keep the INFORMATIVE, and then write a separate AUTHORITATIVE caching agent for applications only.

**Comment by lwander** [comment]
We talked out of band, the fact that each agent prefixes their keys with the agent name means this should still work

**Comment by lwander** [comment]
LGTM

**Pull request merged**
