### PR TITLE
fix(6430): Adding missing block device mappings for new launch templates

### PR DESCRIPTION
**Pull request by pdk27**
fix(6430): Adding missing block device mappings for new launch templates (thanks @JooeunAhn)

https://github.com/spinnaker/spinnaker/issues/6430

### CODE REVIEW

**Review by jeyrschabu — APPROVED** [review]

**Comment by jeyrschabu** [comment]
Worth a test to assert the block devices dare passed.

**Comment by pdk27** [comment]
> Worth a test to assert the block devices are passed.

Sure. I have refactored the `LaunchTemplateServiceSpec` unit tests in my open PRs. Will surely add a test in my next PR, once the refactors are merged.

**Comment by link108** [comment]
@mergifyio backport release-1.26.x

**Comment by link108** [comment]
@Mergifyio backport release-1.25.x

**Pull request merged**
