### PR TITLE
fix(docker): Suppress unnecessary stacktraces when `getTags` returns 404

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by ajordens** [comment]
Just doing some cleaning up of what I'd consider unnecessary stacktraces ... sensible @tomaslin?

**Comment by tomaslin** [comment]
makes sense, wonder if it makes sense to also just log out the message in line 102 since that is super verbose as well

**Comment by tomaslin** [comment]
LGTM otherwise

**Comment by ajordens** [comment]
At this point we're only seeing 404's, so I'm inclined to do a targeted fix. 

If (in the future) we see something else pop up in logs we can circle around.

**Pull request merged**
