### PR TITLE
feat(provider/azure): Enable dns label

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Background:
Currently dns label is specified with default value while creating and updating dns label. So we add an entry to specify the custom dns label while creating and updating dns label. There is a related PR in deck (https://github.com/spinnaker/deck/pull/7065).

### CODE REVIEW

**Comment by neil-yechenwei** [comment]
@duftler , a kindly ping, please help to review it. Thanks.

**Comment by louisjimenez** [comment]
@duftler would you be able to take a look at this when you have a moment? The related [deck pr](https://github.com/spinnaker/deck/pull/7065#discussion_r288825493) looks good

**Comment by neil-yechenwei** [comment]
> @duftler would you be able to take a look at this when you have a moment? The related [deck pr](https://github.com/spinnaker/deck/pull/7065#discussion_r288825493) looks good

@louisjimenez , @duftler , a kindly ping , is there any update?

**Comment by neil-yechenwei** [comment]
@louisjimenez , @duftler , a kindly ping, is there any update?

**Pull request merged**
