### PR TITLE
added os = LINUX to clouddriver-web.gradle for building rpms. does no…

### PR DESCRIPTION
**Pull request by skorten**
…t affect deb, option is ignored

### CODE REVIEW

**Comment by cfieber** [comment]
@skorten have a look at the conversation on #264 and lets figure out the plan there

**Comment by skorten** [comment]
good plan

**Comment by skorten** [comment]
FWIW, this change is just so the rpms build with the correct headers so they can be installed by rpm without using the --ignoreos switch.  WIthout this change rpm complains about "unsupported OS".

**Comment by cfieber** [comment]
yeah I ran into that as well, I think there might be some preInstall/postInstall stuff to do along with this to make the RPMs 1st class

**Comment by skorten** [comment]
agreed.

**Pull request closed without merging**
