### PR TITLE
fix(amazon): allow image lookup of AMIs prefixed with "ami"

### PR DESCRIPTION
**Pull request by anotherchrisberry**
It's been pointed out that we don't let folks search for images whose names start with "ami", e.g. "ami_base". This just expands the search restriction to match on the hyphen.

### CODE REVIEW

**Comment by AgarFu** [comment]
Maybe something like this will reduce the false positives?
``` groovy 
def isAmi = glob ==~ /^ami-[a-z0-9]\{8}$/
```

**Comment by anotherchrisberry** [comment]
I believe the concern is that `ami` will match _every_ image - including public images - which is very taxing on the controller, since it will retrieve all matches, then sort them.

The idea behind the exact length matching on the `ami-xxxxxxxx` string is to perform a much faster (non-globbed) lookup of a known image.

I hope nobody is prefixing their AMI names with `ami-`, but maybe some folks are.

Looking forward to @ajordens chiming in on this...

**Comment by ajordens** [comment]
Seems reasonable to me @anotherchrisberry

**Comment by ajordens** [comment]
If someone searches for `ami`, that isn't going to get treated as an amiId and is going to instead search by image name (`*ami*`). 

```
Collection<String> namedImageIdentifiers = !isAmi ? cacheView.filterIdentifiers(NAMED_IMAGES.ns, namedImageSearch) : []
    Collection<String> imageIdentifiers = namedImageIdentifiers.isEmpty() ? cacheView.filterIdentifiers(IMAGES.ns, imageSearch) : []
```

Is there a fear that if there are no `NAMED_IMAGES.ns` w/ `*ami*` that it will fall through and attempt to fetch all `IMAGES.ns` w/ `*ami*`. 

That sounds unintentional and potentially bad. 

Might be worth explicitly preventing a `*ami*` against `IMAGES.hs`.

**Comment by anotherchrisberry** [comment]
@AgarFu good call on the regex match. I went ahead and refactored this a bit more - does this seem reasonable? It's still going to punish anyone who's prefixing their AMI names with "ami-", but surely nobody does that, right?

**Comment by anotherchrisberry** [comment]
Alternative, as @ajordens said, is to prevent `*ami*` searches against `IMAGES.ns`, which is maybe more legit.

**Pull request merged**
