### PR TITLE
feat(oracle): Adding Oracle back into cloud providers

### PR DESCRIPTION
**Pull request by robzienert**
Oracle now has a SIG.

### CODE REVIEW

**Comment by robzienert** [comment]
@sandeeps2 Trying to re-enable the Oracle cloud provider, but it isn't compiling successfully, can you take a look?

**Comment by sandeeps2** [comment]
> @sandeeps2 Trying to re-enable the Oracle cloud provider, but it isn't compiling successfully, can you take a look?

Ack.

**Comment by maggieneterval** [comment]
@sandeeps2 just FYI a PR against Deck uncommenting [this line](https://github.com/spinnaker/deck/blob/master/app/scripts/app.ts#L29) will also be necessary to replace Oracle support.

**Comment by sandeeps2** [comment]
I tried this change and getting a different error. Any ideas?
```
[clouddriver]$git diff
diff --git a/clouddriver-oracle/clouddriver-oracle.gradle b/clouddriver-oracle/clouddriver-oracle.gradle
index 3ad60611d..c140eace0 100644
--- a/clouddriver-oracle/clouddriver-oracle.gradle
+++ b/clouddriver-oracle/clouddriver-oracle.gradle
@@ -1,6 +1,7 @@
 dependencies {
-  implementation project(":clouddriver-core")
   implementation project(":cats:cats-core")
+  implementation project(":clouddriver-api")
+  implementation project(":clouddriver-core")
   implementation project(":clouddriver-security")
 ```
```
  /home/sanshriv/clouddriver/clouddriver-oracle/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/oracle/security/OracleNamedAccountCredentials.java:11: error: cannot find symbol
  extends AbstractAccountCredentials<java.lang.Object>  implements
          ^
  symbol: class AbstractAccountCredentials
/home/sanshriv/clouddriver/clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/validator/UpsertLoadBalancerDescriptionValidator.java:30: error: cannot find symbol
      List priorDescriptions, UpsertLoadBalancerDescription description, ValidationErrors errors) {
                                                                         ^
  symbol:   class ValidationErrors
  location: class UpsertLoadBalancerDescriptionValidator
/home/sanshriv/clouddriver/clouddriver-oracle/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/oracle/deploy/validator/StandardOracleAttributeValidator.java:20: error: cannot find symbol
public  java.lang.Object validateNotEmptyString(ValidationErrors errors, java.lang.String value, java.lang.String attribute) { return null;}
                                                                                      ^
```
Complains about ValidationErrors

**Comment by sandeeps2** [comment]
> @sandeeps2 just FYI a PR against Deck uncommenting [this line](https://github.com/spinnaker/deck/blob/master/app/scripts/app.ts#L29) will also be necessary to replace Oracle support.

Ok

**Comment by sandeeps2** [comment]
> I tried this change and getting a different error. Any ideas?
> 
> ```
> [clouddriver]$git diff
> diff --git a/clouddriver-oracle/clouddriver-oracle.gradle b/clouddriver-oracle/clouddriver-oracle.gradle
> index 3ad60611d..c140eace0 100644
> --- a/clouddriver-oracle/clouddriver-oracle.gradle
> +++ b/clouddriver-oracle/clouddriver-oracle.gradle
> @@ -1,6 +1,7 @@
>  dependencies {
> -  implementation project(":clouddriver-core")
>    implementation project(":cats:cats-core")
> +  implementation project(":clouddriver-api")
> +  implementation project(":clouddriver-core")
>    implementation project(":clouddriver-security")
> ```
> 
> ```
>   /home/sanshriv/clouddriver/clouddriver-oracle/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/oracle/security/OracleNamedAccountCredentials.java:11: error: cannot find symbol
>   extends AbstractAccountCredentials<java.lang.Object>  implements
>           ^
>   symbol: class AbstractAccountCredentials
> /home/sanshriv/clouddriver/clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/validator/UpsertLoadBalancerDescriptionValidator.java:30: error: cannot find symbol
>       List priorDescriptions, UpsertLoadBalancerDescription description, ValidationErrors errors) {
>                                                                          ^
>   symbol:   class ValidationErrors                                                                                      ^
> ```
> 
> Complains about ValidationErrors

Looks like I need to fix imports at a number of spots.

**Comment by sandeeps2** [comment]
> > I tried this change and getting a different error. Any ideas?
> > ```
> > [clouddriver]$git diff
> > diff --git a/clouddriver-oracle/clouddriver-oracle.gradle b/clouddriver-oracle/clouddriver-oracle.gradle
> > index 3ad60611d..c140eace0 100644
> > --- a/clouddriver-oracle/clouddriver-oracle.gradle
> > +++ b/clouddriver-oracle/clouddriver-oracle.gradle
> > @@ -1,6 +1,7 @@
> >  dependencies {
> > -  implementation project(":clouddriver-core")
> >    implementation project(":cats:cats-core")
> > +  implementation project(":clouddriver-api")
> > +  implementation project(":clouddriver-core")
> >    implementation project(":clouddriver-security")
> > ```
> > 
> > 
> > ```
> >   /home/sanshriv/clouddriver/clouddriver-oracle/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/oracle/security/OracleNamedAccountCredentials.java:11: error: cannot find symbol
> >   extends AbstractAccountCredentials<java.lang.Object>  implements
> >           ^
> >   symbol: class AbstractAccountCredentials
> > /home/sanshriv/clouddriver/clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/validator/UpsertLoadBalancerDescriptionValidator.java:30: error: cannot find symbol
> >       List priorDescriptions, UpsertLoadBalancerDescription description, ValidationErrors errors) {
> >                                                                          ^
> >   symbol:   class ValidationErrors                                                                                      ^
> > ```
> > 
> > 
> > Complains about ValidationErrors
> 
> Looks like I need to fix imports at a number of spots.

Here is the diff of my local changes. I am not able to push to this PR branch.

[diff.txt](https://github.com/spinnaker/clouddriver/files/5096149/diff.txt)

@robzienert Can you apply this diff to this PR or you want me to submit it via another?

Thanks

**Comment by robzienert** [comment]
Updated, thanks!

**Pull request merged**
