### PR TITLE
fix(kubernetes): k8s event timestamp should be null safe

### PR DESCRIPTION
**Pull request by titirigaiulian**
In some cases k8s api returns `lastTimestamp` with null value causing the `ManifestBuilder` to throw nullPointerException.
Made `lastEventTimestamp` optional and set default value for usecases when the key exists in the map but is null

Issue: https://github.com/spinnaker/spinnaker/issues/6181

### CODE REVIEW

**Review by ezimanyi — APPROVED** [review]
Thanks for fixing this!

One suggestion that might make the fix more robust.  It looks like the issue with the `null` is because of the `Comparator` below.

Another way to fix this would be to change below:
```
.sorted(Comparator.nullsLast(Comparator.comparing(lastEventTimestamp)))
```
which makes the comparator null-safe.  This might be a bit more clear than the "n/a" (which I realize is pre-existing already).

Definitely consider this an `Optional<Suggestion>`, this is fine to merge too!

**Comment by titirigaiulian** [comment]
Hey @ezimanyi  thanks for the quick review. Changed a bit to use `Comprator` `nullsLast`, but I had to use it twice to catch also the nulls returned by the `lastEventTimestamp`. Using only `Comparator.nullLast...` will handle the `KubernetesManifest` nulls. 
Can you please take another look?

**Review by andreeagheorghescu — APPROVED** [review]

**Review by ezimanyi — APPROVED** [review]
This looks good to me!  Thanks!

**Comment by titirigaiulian** [comment]
Can this be backported to 1.23?

**Comment by rbadillo** [comment]
We need this fix in 1.23.x please

**Comment by ezimanyi** [comment]
The release branch patch criteria are [here](https://spinnaker.io/community/contributing/releasing/#release-branch-patch-criteria); this would need to fix a documented regression and include tests demonstrating the regression.  If that's the case then there are instructions at that link for requesting a cherry-pick from the current release manager.

**Pull request merged**
