### PR TITLE
feat(ecs): Make ECS agents implement AccountAware

### PR DESCRIPTION
**Pull request by nabuskey**
In preparation for ECS provider to implement `BaseProvider` and `CredentialsRepository` as introduced in [RFC](https://github.com/spinnaker/governance/blob/master/rfc/account-management.md) , ECS agents must implement `AccountAware` to remove agents when credentials are removed from repository. 

@allisaurus

### CODE REVIEW

**Comment by allisaurus** [comment]
@nabuskey can you add some info / output to indicate what kind of testing was done to verify this change? (e.g., screenshot of a successful ECS deployment post-change)

**Comment by nabuskey** [comment]
@allisaurus Here's a successful deployment to ECS Fargate after changes were made. 

image

**Comment by allisaurus** [comment]
thanks @nabuskey ! For my understanding, was [this deployment](https://github.com/spinnaker/clouddriver/pull/5044#issuecomment-717355835) was made with the ECS account mapped to a static (vs. dynamic) AWS account? Or do we expect both scenarios to work at this point? (I assume dynamic _ECS accounts_ won't work until the provider implements the new interfaces, or is that incorrect?)

**Comment by nabuskey** [comment]
The testing was done on a static account since I do not expect dynamic account mapping to work without further modifications to `clouddriver-ecs`. For dynamic ECS accounts to work, the ECS module needs to implement `CredentialsLifecycleHandler`, `AccountParser`, `CredentialsRepository`, and `BaseProvider`. I am working on these, and I wanted to submit this PR alone since it's a self-contained change. ECS agents were already "account aware". They just did not implement the interface.

**Review by allisaurus — APPROVED** [review]
LGTM!

**Pull request merged**
