### PR TITLE
fix(artifacts): resolve version of artifacts

### PR DESCRIPTION
**Pull request by claymccoy**
Sometimes Artifacts don’t have the version populated. For example, a default Maven artifact in a pipeline may have a reference with a ‘latest.release’ suffix. This allows us a way to look up the actual version used. Name is often unpopulated along with version.
This also finds specific snapshot versions.
Artifact Url was purposefully left out of the CF server group env vars because we don’t actually have enough information to construct it and put it in artifact.location upstream.

### CODE REVIEW

**Comment by claymccoy** [comment]
> I suspect we are looking at the wrong artifact. The bound artifact should already contain a resolved version and name.

It does not. If it did, then this would have worked as it was.

**Comment by claymccoy** [comment]
when triggered by an artifact:
```"resolvedExpectedArtifacts": [
{
"boundArtifact": {
"customKind": false,
"location": "https://repo.spring.io/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/com/example/demo/0.0.1-SNAPSHOT",
"metadata": {
"build": {
"created": "2019-05-21T19:38:14.694Z",
"name": "artifactory_buildinfo_maven",
"number": "15",
"url": "https://35.184.36.114/job/artifactory_buildinfo_maven/15/"
}
},
"name": "com.example:demo",
"provenance": "libs-snapshot-local",
"reference": "com.example:demo:0.0.1-SNAPSHOT",
"type": "maven/file",
"version": "0.0.1-SNAPSHOT"
},
"defaultArtifact": {
"customKind": true,
"metadata": {
"id": "e0f90206-a357-43f7-8c6c-1175c54a1dcf"
}
},
"id": "bb8c0db0-2c40-40f9-b3cf-e7a45bdfa4dc",
"matchArtifact": {
"artifactAccount": "spring-artifactory-maven",
"customKind": true,
"metadata": {
"id": "ea0b4f2e-1fb1-4590-80b1-7b4122370bc5"
},
"reference": "com.example:demo:.*",
"type": "maven/file"
},
"useDefaultArtifact": false,
"usePriorArtifact": true
}
]```

**Comment by claymccoy** [comment]
when using the default artifact:
```json
"resolvedExpectedArtifacts": [{
	"boundArtifact": {
		"artifactAccount": "spring-artifactory-maven",
		"customKind": false,
		"metadata": {
			"id": "06d2f7e4-c254-4501-9347-01c65e713225"
		},
		"reference": "io.pivotal.spinnaker:multifoundationmetrics:latest.release",
		"type": "maven/file"
	},
	"defaultArtifact": {
		"artifactAccount": "spring-artifactory-maven",
		"customKind": false,
		"metadata": {
			"id": "06d2f7e4-c254-4501-9347-01c65e713225"
		},
		"reference": "io.pivotal.spinnaker:multifoundationmetrics:latest.release",
		"type": "maven/file"
	},
	"id": "6ccb174c-02a2-4239-8609-95f19c7bd6c9",
	"matchArtifact": {
		"artifactAccount": "spring-artifactory-maven",
		"customKind": true,
		"metadata": {
			"id": "51312a48-9c2c-4b70-bc7a-84d6e91357ea"
		},
		"reference": "io.pivotal.spinnaker:multifoundationmetrics:.*",
		"type": "maven/file"
	},
	"useDefaultArtifact": true,
	"usePriorArtifact": true
}]
```

**Comment by claymccoy** [comment]
Prior artifact populates the bound artifact correctly just like the trigger.

**Comment by jkschneider** [comment]
@spinnakerbot cherry-pick 1.14

**Pull request merged**
