### PR TITLE
Add docker/kubernetes default config

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
@rguthriemsft @scotmoor @lwander @duftler PTAL

**Comment by EricJizbaMSFT** [comment]
This gets used when I'm debugging clouddriver in a dev environment

**Comment by lwander** [comment]
I see - my issue with this is that this change means that this config for Kubernetes will always be shipped with every installation of clouddriver, regardless of whether it's in a dev or prod environment. Now every installation has another layer of config to resolve and to potentially override, which is problematic for fields like "password" vs "passwordFile" where at most one should be specified, now forcing the user to manually set whatever they aren't providing as null/empty.

**Comment by EricJizbaMSFT** [comment]
I see how this could cause issues down the line and there are other methods of setting these in a dev environment, so I'll close this

**Pull request closed without merging**
