### PR TITLE
feat(cloudformation): Treat template as string instead of yaml

### PR DESCRIPTION
**Pull request by gregjones**
To allow for templates containing instinsic functions (e.g. !Ref)
this changes the cloudformation operation so the parameter is processed
as a string, instead of a map.

For backwards compatibility, if the received value is a map, it will
be dumped as a string before continuing.

### CODE REVIEW

**Comment by gregjones** [comment]
cc @xavileon

**Comment by xavileon** [comment]
@spinnaker/reviewers PTAL  related to https://github.com/spinnaker/orca/pull/3024

**Comment by xavileon** [comment]
@ethanfrogers if you could also check out this one, it's related to https://github.com/spinnaker/orca/pull/3024 thanks!

**Comment by ethanfrogers** [comment]
sorry for the delay here @xavileon! it fell off my radar.

**Pull request merged**
