### PR TITLE
new banner

### PR DESCRIPTION
**Pull request by lwander**
@spinnaker/reviewers PTAL

### CODE REVIEW

**Comment by lwander** [comment]
The github font styling isn't too good, it looks a little better here: 
clouddriver-logo

**Comment by jtk54** [comment]
Groovy, baby.

**Comment by cfieber** [comment]
fullofstars

**Comment by gregturn** [comment]
Are they flowers or clouds?

**Comment by lwander** [comment]
Flowers

**Comment by lwander** [comment]
@cfieber Matt filled me in

**Comment by lwander** [comment]
(I can't unsee it either)

**Comment by duftler** [comment]
unceremoniously closed

**Comment by cfieber** [comment]
Aww

**Pull request closed without merging**
