### PR TITLE
fix(aws): Fix bug in AWS provider after Groovy 3 upgrade

### PR DESCRIPTION
**Pull request by jervi**
I'm unsure how this code has ever worked, but after the upgrade to Groovy 3, it started crashing.

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: 
Cannot cast object '{loadBalancers=aws:loadBalancers:my-aws-account:eu-west-1:*:vpc-????????:*}' 
with class 'java.util.LinkedHashMap' to class 'java.util.Optional' due to: groovy.lang.GroovyRuntimeException: 
Could not find matching constructor for: java.util.Optional(LinkedHashMap)
```

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Thanks much!  Possible to add a test for this so we don't break it again in the future?

**Comment by jervi** [comment]
Tests added

**Comment by dbyron-sf** [comment]
Thanks much!

**Review by dbyron-sf — APPROVED** [review]

**Comment by jasonmcintosh** [comment]
Thinking this should backport to 1.33?

**Comment by dbyron-sf** [comment]
> Thinking this should backport to 1.33?

Agreed given https://spinnaker.io/changelogs/1.33.0-changelog/#groovy-3

**Comment by dbyron-sf** [comment]
@mergifyio backport release-1.33.x

**Pull request merged**
