### PR TITLE
(feat/cats) Add support for an error interval for clustered agent sch…

### PR DESCRIPTION
**Pull request by rfarrjr**
…edulers

The following change introduces a new errorInterval used by the ClusteredSortAgentScheduler and ClusteredAgentScheduler.  This interval is used when the Agent throws an exception on a run.

Once this PR is accepted an released a future PR will follow for fiat to leverage this functionality.

This PR is the result of previous discussion with @cfieber.

### CODE REVIEW

**Comment by rfarrjr** [comment]
Thanks.  I can look over the Dynomite scheduler today.   Would you prefer I add it to this PR or create a separate one?

**Comment by robzienert** [comment]
Same one is fine

**Comment by rfarrjr** [comment]
here it is, was't too bad

**Comment by rfarrjr** [comment]
ping @spinnaker/reviewers

**Pull request merged**
