### PR TITLE
fix(provider/kubernetes): fix NPE on KubernetesV2ServerGroup disabled…

### PR DESCRIPTION
**Pull request by ncknt**
KubernetesV2ServerGroup disabled flag is null and causes a NPE.
Related to spinnaker/spinnaker#3490 and cherry picked PRs: #3292, #3293,  #3294

### CODE REVIEW

**Comment by ncknt** [comment]
@ezimanyi Here's #3322 on master this time.

**Comment by ezimanyi** [comment]
Actually as I look at this one more time, we might actually want to treat `null` as equivalent to `false` to be consistent with how this works in the rest of the (groovy) code.  Everywhere else, if this is `null` it will be treated as false as `!serverGroup.isDisabled()` will be true whether `isDisabled` returns `false` or `null`.  It *probably* doesn't matter that much, but is probably better to be consistent.

Would like @lwander to take a look before merging

**Comment by ncknt** [comment]
I'd expect `null` to be equivalent of `false`. Isn't it what we're doing here?

**Comment by ezimanyi** [comment]
No, it took me a second read to realize this:
```
a != null && !a
false when a == null
true when a == false
```

I think we'd want
```
(a == null || !a)
```

**Comment by ncknt** [comment]
haha. Not my day, thanks for double checking. I've updated the PR.

**Comment by lwander** [comment]
@spinnakerbot cherry-pick 1.12

**Comment by ezimanyi** [comment]
@ncknt : Was it 1.10 where you wanted this fix?  If so, we can cherry-pick into 1.11 and 1.10 as well

**Comment by ncknt** [comment]
@ezimanyi Yes 1.10 and 1.11 would be great too.

**Comment by ezimanyi** [comment]
@spinnakerbot cherry-pick 1.11

**Comment by ezimanyi** [comment]
@spinnakerbot cherry-pick 1.10

**Pull request merged**
