### PR TITLE
Allow server group max size and min size to be the same.

### PR DESCRIPTION
**Pull request by varikin**

### CODE REVIEW

**Comment by varikin** [comment]
@spinnaker/reviewers PTAL

**Comment by lwander** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
needs a rebase

**Comment by varikin** [comment]
Rebased

**Comment by anotherchrisberry** [comment]
sorry, can you rebase one more time?

**Comment by varikin** [comment]
How about now?

**Pull request merged**
