### PR TITLE
Avoid an NPE when logging a search provider exception

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
just do it

**Comment by ajordens** [comment]
FYI @jeyrschabu

**Comment by jeyrschabu** [comment]
Thanks @ajordens. also curious why the exception cause is null

**Comment by ajordens** [comment]
@jeyrschabu It's probably 50/50 that an exception will have a cause ... 

ie)
```
throw new IllegalStateException("foobar")
```

**Pull request merged**
