### PR TITLE
fix(image): don't add beginning glob to image search

### PR DESCRIPTION
**Pull request by emjburns**
When we're searching for an image, there doesn't seem to be a reason why we should add a glob to the front of the query here. Specifying a package of `ate` (query like `find?q=ate`) in a find image stage would lead match `gate`, which doesn't seem like desired behavior. 

Is there some scenario I'm missing here where the first `*` is needed?

### CODE REVIEW

**Comment by ajordens** [comment]
breaking change ... not sure it's fair to call something that's been in-place for 4 years a bug?

**Comment by ajordens** [comment]
Since Chris added the globbing, might have something to do with ami searching on the deploy modal. 

Might be a subtle change there but not hugely breaking.

**Comment by emjburns** [comment]
The globbing is needed for the ui dropdown fields. We should add the globs where needed in the UI before merging this PR

**Comment by robzienert** [comment]
Closing - seems this isn't going anywhere for now.

**Pull request closed without merging**
