### PR TITLE
fix(aws): cli version upgrade to support eks auth

### PR DESCRIPTION
**Pull request by pieterza**
AWS have introduced another way of cluster authentication, natively within the `aws` cli.  This allows cluster auth to be done without heptio/aws-authenticator.

See: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

I've submitted a PR earlier which upgraded the awscli to support the eks namespace.
Unfortunately, the version I selected in that PR while adding `eks` was still too old to also have the `get-token` command which will allow the native aws auth being used instead of heptio/aws-authenticator.

Please upgrade the version again, and I apologise for not just setting it to latest back then.

Original PR: https://github.com/spinnaker/clouddriver/pull/3848

### CODE REVIEW

**Comment by pieterza** [comment]
cc @xavileon @ajordens

**Comment by pieterza** [comment]
If possible, can this be added as a hotfix to the current release from Friday?  This is where I realised my initial version change was still too old.

**Comment by pieterza** [comment]
@cfieber :)

**Comment by pieterza** [comment]
More info:

As per https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

aws cli now supports get-token within the eks command namespace.
My initial version bump only added the eks command namespace, but lacks the get-token subcommand.

This new PR ensures this is fixed.

**Comment by pieterza** [comment]
bump.  @claymccoy @xavileon @ajordens 

FYI, Spinnaker -> EKS literally doesn't work without this patch when using the new proposed authentication method.
Please approve & merge :)

**Comment by pieterza** [comment]
@ezimanyi :)

**Comment by robzienert** [comment]
Closing in favor of https://github.com/spinnaker/clouddriver/pull/3907

**Pull request closed without merging**
