### PR TITLE
Couple DescriptionPreProcessors to correct legacy descriptions

### PR DESCRIPTION
**Pull request by ajordens**
- asgName -> serverGroupName
- ResizeAsgDescription now only supports the nested { asgs: [] } structure

### CODE REVIEW

**Comment by ajordens** [comment]
This is pending addressing the feedback @ https://github.com/spinnaker/clouddriver/pull/305

**Comment by anotherchrisberry** [comment]
@ajordens is this ready or do you still want to make some changes?

**Comment by ajordens** [comment]
@anotherchrisberry I've not had any cycles to address the improvements from #305.

**Comment by anotherchrisberry** [comment]
ping

**Pull request closed without merging**
