### PR TITLE
Locks down AccountCredentialsProvider to only return credentials to t…

### PR DESCRIPTION
**Pull request by ttomsu**
…hose who have the proper Spinnaker headers.

I don't think this change will actually do much. Deck will request `/credentials`, but doesn't really do much with that information AFAICT. 

@ajordens @cfieber @duftler @jtk54 PTAL.

### CODE REVIEW

**Comment by cfieber** [comment]
This may cause some problems - we have a few cases where we do service to service calls to look up account level configuration ( AmazonServerGroupCreator in orca as an example ). While we should be enforcing that the right permissions are in play there, in the case of a triggered pipeline I am not sure we have populated the AuthenticatedRequest context sufficiently to propagate credentials to clouddriver.

**Comment by ttomsu** [comment]
Spoke with @cfieber offline - We think that this won't break triggered pipelines for the reasons above because triggered pipelines are not supported for accounts with `requiredGroupMembership`

I'll still run a pipeline test to ensure this doesn't break, and will report back.

**Comment by anotherchrisberry** [comment]
@ttomsu how did your testing go? Are we good with this change?

**Comment by ttomsu** [comment]
@anotherchrisberry No - it turns out that when building up the User in Gate, it makes the call to get all accounts and filters them in Gate. So I'd have to pass the roles instead, which is a much larger change and it's not where we want to go long term.

**Pull request closed without merging**
