### PR TITLE
fix(kubernetes): fix image resolution for project clusters view

### PR DESCRIPTION
**Pull request by maggieneterval**
As noted in comments on this issue (https://github.com/spinnaker/spinnaker/issues/3490), image names were not being resolved for Kubernetes v2 clusters. `KubernetesV2ServerGroup` was missing a `getImagesSummary` method, and the `ProjectClustersService.ApplicationClusterModel` was assuming only one image per cluster.

Before:
before

After:
after

### CODE REVIEW

**Comment by link108** [comment]
@spinnakerbot cherry-pick 1.11

**Comment by ezimanyi** [comment]
@spinnakerbot cherry-pick 1.12

**Comment by ezimanyi** [comment]
Whoops, I guess this was already in 1.12, nevermind @spinnakerbot

**Comment by maggieneterval** [comment]
^^I apppreciate the politeness to @spinnakerbot.

**Pull request merged**
