### PR TITLE
auto start clouddriver service if clouddriver is installed standalone issue #762

### PR DESCRIPTION
**Pull request by peterpd**
this change works together with PR by @ewiseblatt
https://github.com/spinnaker/spinnaker/pull/784

### CODE REVIEW

**Comment by ewiseblatt** [comment]
I'll approve this after I get my other PR in

**Comment by duftler** [comment]
@ewiseblatt this PR is still oustanding.
Needs a rebase.

**Comment by ewiseblatt** [comment]
@peterpd

**Comment by peterpd** [comment]
rebased.
thanks,
peter

**Comment by ewiseblatt** [comment]
How do I re-trigger travis? it looks like it timed out, but dont see a way to force a retry.

**Comment by tomaslin** [comment]
@ewiseblatt click on details link next to travis icon, log in and then click on the refresh button

**Pull request merged**
