### PR TITLE
optional cache value compression

### PR DESCRIPTION
**Pull request by cfieber**
WIP do not merge
- adds optional compression to cache values
- adds spectator metrics for `RedisCache.CacheMetrics`

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
still WIP or should we close?

**Comment by ajordens** [comment]
Thoughts @cfieber ... this has been on the vine for sometime, I'm not sure where it eventually got in terms of validation / things still working.

**Comment by ewiseblatt** [comment]
please reap this @cfieber

**Comment by robzienert** [comment]
Can be reopened if it needs revisiting.

**Pull request closed without merging**
