### PR TITLE
feat(yandex): add a new cloud provider

### PR DESCRIPTION
**Pull request by vasiliy-briginets**
This is the set of features needed to make Yandex.Cloud usable as a provider in Spinnaker.

Proposal - https://github.com/spinnaker/governance/issues/166

### CODE REVIEW

**Comment by vasiliy-briginets** [comment]
@spinnaker/reviewers

**Review by robzienert — APPROVED** [review]
Did not review, but will approve since it's all in a separate cloud provider module. Smaller PRs in the future are beneficial.

**Comment by vasiliy-briginets** [comment]
> Did not review, but will approve since it's all in a separate cloud provider module. Smaller PRs in the future are beneficial.

sure :) This is the full-feature-covered PR for our provider, so it couldn't be smaller

**Comment by robzienert** [comment]
Looks like tests are failing, though.

**Pull request merged**
