### PR TITLE
provide/openstack: provider delegation

### PR DESCRIPTION
**Pull request by drmaas**

### CODE REVIEW

**Comment by drmaas** [comment]
@spinnaker/reviewers ptal. Will squash once ready to merge.

**Comment by lwander** [comment]
LGTM since this seems contained to the openstack provider. If you want spinnaker/reviewers to actually review this stuff please submit PRs in digestible chunks.

**Comment by drmaas** [comment]
@lwander 99% of this was moving code around, and so I am not expecting a review of that existing code. 

That said, apologies for such a large PR, I know it's not easy to read.

**Comment by lwander** [comment]
No worries, just offering in case you want close reviews. Squashed & merged for you.

**Pull request merged**
