### PR TITLE
fix(provider/kubernetes): Rebase K8s client staging branch

### PR DESCRIPTION
**Pull request by chlung**
Hi,

We need to catch up the master code. This is the PR about.

Thanks.

We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

### CODE REVIEW

**Comment by chlung** [comment]
@lwander Please review and instruct the next step.

**Comment by lwander** [comment]
I will merge - but I feel that this might not be everything we need to do. Let me check after the merge goes through.

**Comment by chlung** [comment]
@lwander  thanks.  We still have a couple of bugs in discovery function, and we will try to fix them asap.

**Comment by lwander** [comment]
yfdqxvru348
^ this upstream branch is still behind master - I think you will need to rebase your local k8s-client-staging branch against upstream/master and push that

**Comment by chlung** [comment]
@lwander ok.  let me try.  thanks

**Pull request merged**
