### PR TITLE
provider/openstack: add desired field to server group capacity object

### PR DESCRIPTION
**Pull request by drmaas**

### CODE REVIEW

**Comment by drmaas** [comment]
@spinnaker/reviewers

**Comment by lwander** [comment]
LGTM - does this need to be merged in any special order w.r.t. https://github.com/spinnaker/clouddriver/pull/890 ?

**Comment by drmaas** [comment]
@lwander probably after should be fine.

**Comment by lwander** [comment]
890 is merged - needs a rebase

**Pull request merged**
