### PR TITLE
fix(artifacts/bitbuket): added ACCEPT Header when using token auth

### PR DESCRIPTION
**Pull request by Avi1235**
When using an invalid token without the header `Accept: application/json` we get 302 response back and `okHttpClient.newCall(request).execute().isSuccessful()` returns true thus sending orca the incorrect ResponseBody

Screen Shot 2022-11-16 at 8 37 49 AM
Screen Shot 2022-11-16 at 8 31 06 AM

**-----------------------------------------------------------------------------------------------------------------**

With the header in place we get 401 `okHttpClient.newCall(request).execute().isSuccessful()` returns false thus throwing the correct exception and error log from clouddriver
tested on spinnaker and using curl:
Screen Shot 2022-11-16 at 8 40 18 AM
Screen Shot 2022-11-16 at 8 30 10 AM

### CODE REVIEW

**Review by nemesisOsorio — APPROVED** [review]

**Review by ovidiupopa07 — APPROVED** [review]

**Review by ovidiupopa07 — COMMENTED** [review]
hi @Avi1235 . Are there any tests that we can add for this?

**Comment by Avi1235** [comment]
Hello @ovidiupopa07 yes I added the `Accept: application/json` header on the unit tests, workflows need to be ran again :bowtie:

**Comment by Avi1235** [comment]
My bad [spotlessJavaCheck failed ](https://github.com/spinnaker/clouddriver/actions/runs/3490270028/jobs/5841606555)
care to re-run them? @dbyron0

**Review by mattgogerly — APPROVED** [review]

**Review by mattgogerly — APPROVED** [review]

**Comment by dogonthehorizon** [comment]
@mattgogerly I haven't taken the time to dig into why this is happening, but we're noticing it on some of our PRs as well. For now I'll merge and backport myself.

**Comment by dogonthehorizon** [comment]
@mergifyio backport release-1.28.x release-1.29.x

**Pull request merged**
